---
title: "lnRR"
author: "Gabriel Melhado"
date: "2025-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
pacman::p_load(devtools, tidyverse, metafor, patchwork, R.rsp, orchaRd, emmeans, ape, phytools, flextable, here, kableExtra, magrittr, metagear, rotl, clubSandwich, MuMIn, ggsankey, scales)
```

```{r}
# Load Data
data <- read.csv(here("data", "data_pharma_immune.csv"))

```

```{r}
## Calculate effect sizes and sampling variances
# Make sure all data is numeric 
data <- data  %>%
  mutate(
    treatment_mean = as.numeric(treatment_mean),
    treatment_sd = as.numeric(treatment_sd),
    treatment_n = as.numeric(treatment_n),
    control_mean = as.numeric(control_mean),
    control_sd = as.numeric(control_sd),
    control_n = as.numeric(control_n)
  )

# Calculate log response ratio (lnRR)
lnRR <- escalc(measure = "ROM", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)


# Calculate log coefficient variation ratio (lnCVR)
lnCVR <- escalc(measure = "CVR", 
                m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
                m2i = control_mean, sd2i = control_sd, n2i = control_n, 
                data = data)

# Calculate the standardised mean difference for sensitivity analysis
SMD <- escalc(measure = "SMD", 
              m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
              m2i = control_mean, sd2i = control_sd, n2i = control_n, 
              data = data)

# Calculate log variation ratio (lnVR)
lnVR <- escalc(measure = "VR", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)

# Summary statistics of sampling variances
sampling_variance_summaries <- list(
  lnRR = summary(lnRR$vi),
  lnCVR = summary(lnCVR$vi),
  SMD = summary(SMD$vi),
  VR = summary(lnVR$vi)
)

# Calculate precision for each effect size estimate with checks
lnRR$precision <- ifelse(lnRR$vi > 0, 1 / sqrt(lnRR$vi), NA)
lnCVR$precision <- ifelse(lnCVR$vi > 0, 1 / sqrt(lnCVR$vi), NA)
SMD$precision <- ifelse(SMD$vi > 0, 1 / sqrt(SMD$vi), NA)
lnVR$precision <- ifelse(lnVR$vi > 0, 1 / sqrt(lnVR$vi), NA)


# Merge the data
effect_size_metrics_set <- data.frame(
  lnRR = lnRR$yi, lnRRv = lnRR$vi, lnRR_precision = lnRR$precision,
  lnVR = lnVR$yi, lnVRv = lnVR$vi, lnVR_precision = lnVR$precision,
  lnCVR = lnCVR$yi, lnCVRv = lnCVR$vi, lnCVR_precision = lnCVR$precision,
  SMD = SMD$yi, SMDv = SMD$vi, SMD_precision = SMD$precision,
  control_imputed = data$control_sd, treatment_imputed = data$treatment_sd
)

# Bind the effect size metrics set to the main data
data <- cbind(data, effect_size_metrics_set)

#Flip the sign (change effect sizes direction)
data <- subset(data, orientation != 0) #Remove immune traits with orientation "0"
data$lnRR <- ifelse(data$orientation == "-1", -1 * data$lnRR, data$lnRR)


# Select specific columns including the new precision columns
effect_size_metrics_set_kable <- data[, which(colnames(data) %in% c(
  "study_id","assay_id", "species_english", "pharmaceutical", "immune_trait_category",
  "lnRR", "lnRRv", "lnRR_precision", 
  "lnCVR", "lnCVRv", "lnCVR_precision", 
  "lnVR", "lnVRv", "lnVR_precision", 
  "SMD", "SMDv", "SMD_precision", 
  "control_imputed", "treatment_imputed"
))] %>% dfround(digits = 3)

# Table of the effect sizes
kable(effect_size_metrics_set_kable, "html") %>%
  kable_styling("bordered", position = "left") %>%
  scroll_box(width = "250%", height = "800px")

# Figure 1
# Plot the distribution of effect size estimates (lnRR)
theme_pub <- theme_bw(base_size = 10) +
  theme(
    legend.position = "none",
    
    # Axis titles
    axis.title = element_text(
      face = "bold",
      size = 11,
      color = "black"
    ),
    
    # Axis text (numbers)
    axis.text = element_text(
      size = 10,
      color = "black"
    ),
    
    # Axis lines and ticks
    axis.ticks = element_line(color = "black", linewidth = 0.4),
    axis.line = element_line(color = "black", linewidth = 0.4),
    
    # Remove grid
    panel.grid = element_blank(),
    
    # Panel border slightly stronger
    panel.border = element_rect(color = "black", linewidth = 0.5)
  )

lnRR_dist_plot <- effect_size_metrics_set_kable %>%
  ggplot(aes(lnRR)) +
  geom_histogram(
    fill = "#BFD3E6",
    color = "black",
    binwidth = 0.1,
    linewidth = 0.3
  ) +
  labs(
    x = "Log Response Ratio (lnRR)",
    y = "Frequency"
  ) +
  theme_pub



print(lnRR_dist_plot)
```

```{r}
## Dependent effect size estimates
# Create phylogenetic tree

data <- as.data.frame(data)

data$species_latin = as.factor(data$species_latin)

taxa <- tnrs_match_names(names = levels(data$species_latin), context = "Animals")  # Match species names to the Open Tree of Life taxonomy

kable(taxa)  # Display matched species, ensuring each species has a unique match in the Open Tree of Life

taxa$unique_name <- gsub(" ", "_", taxa$unique_name)  # Replace spaces in species names with underscores

phylo_tree <- tol_induced_subtree(ott_ids = taxa$ott_id, label_format = "name")  # Generate a phylogenetic tree based on the Open Tree of Life taxonomy

ott_in_tree <- ott_id(taxa)[is_in_tree(ott_id(taxa))]  # Ensure all identifiers are present in the taxonomy

phylo_tree <- tol_induced_subtree(ott_ids = ott_in_tree)  # Generate a phylogenetic tree including all species present in the taxonomy

is.binary(phylo_tree)  # Check if tree is binary 


# Plot for the phylogenetic tree
plot(phylo_tree,
     cex= 1, #font size
     label.offset =.1,
     no.margin = TRUE)

# Compute branch length
phylo_branched <- compute.brlen(phylo_tree, method = "Grafen", power = 1)  # compute branch lengths using Grafen's method

phylo_branched$tip.label <- strip_ott_ids(phylo_branched$tip.label, remove_underscores = FALSE)  # remove ott ID from species name to match it to the data set

phylo_matrix <- vcv(phylo_branched, cor = T)  # Generate variance covariance matrix to correlate species relatedness 

data <- as.data.frame(data)
data <- data[, !duplicated(names(data))]

# Convert species_latin to lowercase
data <- mutate(data, search_string = tolower(species_latin))

data <- left_join(data, select(taxa, search_string, unique_name, ott_id), by = "search_string")  # Join data sets

data <- data[data$unique_name %in% phylo_branched$tip.label, ]  # Check that species names are well matched with the phylogenetic tree


data$phylogeny <- data$unique_name  # Rename 'unique_name' to 'phylogeny' for the models

```


```{r}
## Variance covariance matrices
# To account for the dependency of effect sizes estimates due to being in the same exposure group (cohort) we constructed a series of vcv matrices.

#------------------------------lnRR------------------------------#
data<- data[!is.na(data$lnRRv),] 
lnRRVCV <- metafor::vcalc(vi = lnRRv, cluster = exposure_id, obs = assay_id, data = data, rho = 0.5)
lnRRVCV <- lnRRVCV + diag(1e-5, nrow(lnRRVCV))

```

```{r}
### Selection of random-effect structure
## Null model with no random effects (lnRR)
# fit a null model as default model
null_mod_lnRR <- rma.mv(yi = lnRR, 
                        V = lnRRVCV, 
                        method = "ML", 
                        test = "t", 
                        data = data, 
                        sparse = TRUE ) # Use ML to compare information criteria

summary(null_mod_lnRR)
```

```{r}
## Add *assay_id* as a random effect and compare with the null model (lnRR)
mod_lnRR.assay_id <- rma.mv(yi = lnRR, 
                            V = lnRRVCV,
                            random =  ~1 | assay_id,
                            method = "ML", 
                            test = "t", 
                            data = data, 
                            sparse = T)

summary(mod_lnRR.assay_id)

anova(null_mod_lnRR,mod_lnRR.assay_id)
```

```{r}
## Add *study_id* as a random effect to the null model and compare with the assay model (lnRR)
mod_lnRR.assay_id.study_id <- rma.mv(yi = lnRR,
                                     V = lnRRVCV,
                                     random = list(~1 | study_id, 
                                                   ~1 | assay_id),
                                     method = "ML",
                                     test = "t", 
                                     data = data, 
                                     sparse = T)

summary(mod_lnRR.assay_id.study_id)

anova(mod_lnRR.assay_id,mod_lnRR.assay_id.study_id)

```

```{r}
## Add *exposure_id* as a random effect to the above model (that used *assay_id* and *study_id* as random effets) (lnRR)
mod_lnRR.assay_id.study_id.exp_id <- rma.mv(yi = lnRR,
                                            V = lnRRVCV,
                                            random = list(~1 | study_id,
                                                          ~1 | exposure_id,
                                                          ~1 | assay_id),
                                            method = "ML",
                                            test = "t", 
                                            data = data,
                                            sparse = T)

summary(mod_lnRR.assay_id.study_id.exp_id)

anova(mod_lnRR.assay_id.study_id,mod_lnRR.assay_id.study_id.exp_id)
```

```{r}
## Add *phylogeny* as a random effect to the better model (that used *assay_id* and *study_id* as random effects) (lnRR)
mod_lnRR.assay_id.study_id.species.phylogeny <- rma.mv(yi = lnRR,
                                                       V = lnRRVCV,
                                                       random = list(~1 | study_id,
                                                                     ~1 | assay_id,
                                                                  
~1 | phylogeny),
                                                       method = "ML",
                                                       test = "t", 
                                                       data = data, 
                                                       sparse = T,
                                                       R = list(phylogeny = phylo_matrix))

summary(mod_lnRR.assay_id.study_id.species.phylogeny)

anova(mod_lnRR.assay_id.study_id,mod_lnRR.assay_id.study_id.species.phylogeny)
```


```{r}
## Add *pharmaceutical* as a random effect to the better model (that used *assay_id* and *study_id* as random effects) (lnRR)
mod_lnRR.assay_id.study_id.pharmaceutical <- rma.mv(yi = lnRR,
                                                       V = lnRRVCV,
                                                       random = list(~1 | study_id,
                                                                     ~1 | assay_id,
                                                                     ~1 | pharmaceutical),
                                                       method = "ML",
                                                       test = "t", 
                                                       data = data, 
                                                       sparse = T)

summary(mod_lnRR.assay_id.study_id.pharmaceutical)

anova(mod_lnRR.assay_id.study_id, mod_lnRR.assay_id.study_id.pharmaceutical)

i2_ml(mod_lnRR.assay_id.study_id.pharmaceutical)

```


```{r}
### Question: Does pharmaceutical impact fish immunocompetence?

## Intercept only meta-analysis models
#Intercept only model (lnRR)

lnRR_intercept_only <- rma.mv(yi = lnRR,
                              V = lnRRVCV,
                              random = list(~1 | study_id,
                                            ~1 | assay_id,
                                            ~1 | pharmaceutical,
                                            ~1 | species_latin,
                                            ~1 | phylogeny),
                              method = "REML",
                              test = "t", 
                              data = data,
                              sparse = T,
                              R = list(phylogeny = phylo_matrix))

# Summary statistics 
summary(lnRR_intercept_only)

mod_results(lnRR_intercept_only, mod = "1", data = data, group = "study_id")  # For prediction intervals

i2_ml(lnRR_intercept_only)

# Given point estimate of lnRR
lnRR_point <- lnRR_intercept_only$b[[1]]

# Calculate the percentage change
lnRR_percentage_change <- (1 - exp(lnRR_point)) * 100
lnRR_percentage_change
```

```{r}
## Figure 2
#Impacts of pharmaceutical exposure on fish immune response. The model estimates the average effects of pharmaceutical exposure on fish immune responses. (a) shows the mean difference between control and treatment groups on a logarithmic scale, where negative values indicate a weak immune response, and positive values indicate a strong immune response.Shorter whiskers represent 95% confidence intervals, while longer whiskers indicate 95% prediction intervals. 'k' represents the number of effect sizes, and the number of studies is in brackets. Each circle corresponds to an effect size, with its size scaled by precision (the inverse of the sampling error variance)

# Figure 2

metric_colours <- list(
  lnRR = "#BFD3E6",
  lnVR = "#F7C9A9"
)

theme_pub_large <- theme_bw(base_size = 13) +
  theme(
    legend.position = "none",

    axis.title = element_text(face = "bold", size = 14, color = "black"),
    axis.text  = element_text(size = 13, color = "black"),

    axis.ticks = element_line(color = "black", linewidth = 0.4),
    axis.line  = element_line(color = "black", linewidth = 0.4),

    panel.grid = element_blank(),
    panel.border = element_rect(color = "black", linewidth = 0.5)
  )


intercept_only.lnRR_orchard <- orchaRd::orchard_plot(
  lnRR_intercept_only,
  group = "study_id",
  xlab = "Log Response Ratio (lnRR)",
  g = TRUE,
  k.pos = "right",
  colour = FALSE,
  fill = TRUE,
  trunk.size = 0.8,
  legend.pos = "none",
  branch.size = 1.5,
  twig.size = 0.5
) +
  scale_fill_manual(values = metric_colours$lnRR) +
  scale_x_discrete(labels = c("Model estimates")) +
  theme_pub_large +
  theme(
    axis.title = element_text(face = "bold", size = 12, color = "black"),
    axis.text  = element_text(size = 11, color = "black"),
    axis.text.y = element_text(face = "bold", size = 13, color = "black", angle = 90, vjust = 0.5, hjust = 0.5),
    panel.grid = element_blank()
  )



# Display
intercept_only.lnRR_orchard

#ggsave(here("figures", "figure1_overall_lnRR.pdf"), width = 12, height = 7, units = "cm", scale = 2, dpi = 800)
#ggsave(here("figures", "figure1_overall_lnRR.jpg"), width = 12, height = 7, units = "cm", scale = 2, dpi = 800)


```


```{r}
#### Question: Do immune traits differ in their responses to pharmaceutical exposure?

## Single moderator meta-regression
# Immune categories (lnRR)

lnRR_mod_immune_category_high <- rma.mv(yi = lnRR,
                                   V = lnRRVCV,
                                   random = list(~1 | study_id,
                                                 ~1 | assay_id,
                                                 ~1 | pharmaceutical,
                                                 ~1 | species_latin,
                                                 ~1 | phylogeny),
                                   mods = ~immune_category_high -1,
                                   method = "REML",
                                   test = "t", 
                                   data = data,
                                   sparse = T,
                                   R = list(phylogeny = phylo_matrix))


# Summary results
summary(lnRR_mod_immune_category_high)

mod_results(lnRR_mod_immune_category_high, mod = "immune_category_high", data = data, group = "study_id")  

r2_ml(lnRR_mod_immune_category_high)

# Extract named estimates from the model
estimates_immune_category_high <- lnRR_mod_immune_category_high$b

# Compute % change for all estimates
lnRR_percentage_change <- (1 - exp(estimates_immune_category_high)) * 100

# View results
lnRR_percentage_change

```


```{r}
# Figure 3
# The moderating effects of immune traits, white blood cell count (WBC), humoral-mediated response, cytokines and cell-mediated response on response magnitude

pal_pastel_named <- c(
  "WBC"          = "#8FBCE6",
  "Humoral-mediated" = "#F7C9A9",
  "Cytokines"    = "#D1B3E0",
  "Cell-mediated"= "#9FD5C0"
)


# Figure 3 (lnRR ~ immune_category_high)

immune_category_high_mod_orchard.lnRR <-
  orchaRd::orchard_plot(
    lnRR_mod_immune_category_high,
    group = "study_id",
    xlab  = "Log Response Ratio (lnRR)",
    mod   = "immune_category_high",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,   # summary CI line
    branch.size = 1.2,   # study CI lines
    twig.size   = 0.8    # study dots
  ) +
  # Pastel fill (use named palette if possible)
  scale_fill_manual(values = pal_pastel_named) +
  # Reference line (no effect)
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", linewidth = 0.4) +
  # Apply the same publication theme
  theme_pub_large +   # swap to theme_pub if single standalone figure
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    # Make category labels clear + black (and bold if you want)
    axis.text.y = element_text(face = "bold", color = "black")
  ) +
  labs(title = NULL)

# shrink the summary bubble and the PI line on the summary layer
immune_category_high_mod_orchard.lnRR$layers[[4]]$geom_params$fatten    <- 1.7  # default is 4
immune_category_high_mod_orchard.lnRR$layers[[4]]$geom_params$linewidth <- 0.35 # ggplot ≥3.4

immune_category_high_mod_orchard.lnRR

```


```{r}
## Question: Do pharmaceuticals vary in their effects on fish immunocompetence?

# Moderate by pharmaceutical_class (lnRR)
lnRR_mod_pharmaceutical <- rma.mv(yi = lnRR,
                                  V = lnRRVCV,
                                  random = list(~1 | study_id,
                                                 ~1 | assay_id,
                                                 ~1 | species_latin,
                                                 ~1 | phylogeny,
                                                 ~1 | pharmaceutical),
                                  mods = ~pharmaceutical_class -1,
                                  method = "REML",
                                  test = "t", 
                                  data = data,
                                  sparse = T,
                                  R = list(phylogeny = phylo_matrix))

# Summary results
summary(lnRR_mod_pharmaceutical)

lnRR_pharmaceutical_mod_results <- mod_results(lnRR_mod_pharmaceutical, mod = "pharmaceutical_class", data = data, group = "study_id") 

r2_ml(lnRR_mod_pharmaceutical)

```


```{r}
## Figure 4
# The moderating effects of pharmaceutical_class on response magnitude 

pharma_colours <- c(
  "Antibiotic"       = "#D1B3E0",  # blue (WBC tone, consistent)
  "Antidepressant"   = "#F7C9A9",  # orange
  "Contraceptive"    = "#8FBCE6",  # purple
  "Anti-inflammatory" = "#9FD5C0" # teal
)

# Build the orchard
pharmaceutical_mod_orchard.lnRR <-
  orchaRd::orchard_plot(
    lnRR_mod_pharmaceutical,
    group = "study_id",
    xlab  = "Log Response Ratio (lnRR)",
    mod   = "pharmaceutical_class",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,
    branch.size = 1.2,
    twig.size   = 0.8
  ) +
  scale_fill_manual(values = pharma_colours) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", linewidth = 0.4) +
  theme_pub_large +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.y = element_text(face = "bold", color = "black")
  ) +
  labs(title = NULL)

# Shrink the big summary bubble (layer [[4]] is the summary pointrange)
pharmaceutical_mod_orchard.lnRR$layers[[4]]$geom_params$fatten    <- 1.7 # default ~4

# slim the CI lines (layers [[3]] & [[4]])
pharmaceutical_mod_orchard.lnRR$layers[[3]]$geom_params$linewidth <- 0.35
pharmaceutical_mod_orchard.lnRR$layers[[4]]$geom_params$linewidth <- 0.35

pharmaceutical_mod_orchard.lnRR

```


```{r}
## Moderate by concentration of pharmaceutical (lnRR)
# Create dataframe for model with consistent dosage units

unique_dosage_units <- unique(data$dosage_unit)
print(unique_dosage_units)

data_dosage <- data %>% 
  mutate(dosage = as.numeric(dosage),
         dosage_unit = as.character(dosage_unit),
         dosage_unit_consistent = case_when(
           dosage_unit == "mg/L" ~ "ug/L", 
           dosage_unit == "ng/L" ~ "ug/L",
           dosage_unit == "ppm" ~ "ug/L", 
           TRUE ~ dosage_unit),
         dosage_convert_ugL = case_when(
           dosage_unit == "mg/L" ~ dosage * 1000,
           dosage_unit == "ng/L" ~ dosage / 1000,
           dosage_unit == "ppm" ~ dosage*1000, 
           TRUE ~ dosage)) %>% 
   filter(!is.na(dosage_convert_ugL)) %>% 
    mutate(log_dosage_convert_ugL = log(dosage_convert_ugL)) 

#Summary table for the dosage converted
summary_data_dosage <- summary(data_dosage$dosage_convert_ugL)
```


```{r}
## Question: Does pharmaceutical dosage influence the magnitude of effects on fish immunocompetence?
# Recalculate the VCV matrix based on the new data frame 
lnRRVCV_dosage <- metafor::vcalc(vi = lnRRv, cluster = exposure_id, obs = assay_id, data = data_dosage, rho = 0.5)


# Model - dosage (lnRR)
lnRR_mod_dosage <- rma.mv(yi = lnRR,
                          V = lnRRVCV,
                          random = list(~1 | study_id,
                                                 ~1 | assay_id,
                                                 ~1 | pharmaceutical,
                                                 ~1 | species_latin,
                                                 ~1 | phylogeny),
                                        
                          mods = ~log_dosage_convert_ugL - 1,
                          method = "REML",
                          test = "t", 
                          data = data_dosage,
                          sparse = T,
                          R = list(phylogeny = phylo_matrix))

# Summary results 
summary(lnRR_mod_dosage)

dosage_mod_lnRR_results <- mod_results(lnRR_mod_dosage, 
        mod = "log_dosage_convert_ugL",
        data = data_dosage, 
        group = "study_id")  

r2_lnRR_dosage <- r2_ml(lnRR_mod_dosage, data_dosage)
r2_lnRR_dosage

```


```{r}
#create the violin plot
med <- median(data_dosage$dosage_convert_ugL, na.rm = TRUE)
q1  <- quantile(data_dosage$dosage_convert_ugL, 0.25, na.rm = TRUE)
q3  <- quantile(data_dosage$dosage_convert_ugL, 0.75, na.rm = TRUE)


# Filter the data for dosage_convert_ugL less than 1000
filtered_data_dosage <- data_dosage %>%
  filter(dosage_convert_ugL < 1000)

p_log <- ggplot(filtered_data_dosage, aes(x = "", y = dosage_convert_ugL)) +
  geom_violin(fill = "#8ED7C6", alpha = 0.35, color = NA, width = 1) +
  geom_boxplot(width = 0.12, outlier.shape = NA,
               color = "#F28E2B", fill = NA, linewidth = 0.9) +
  geom_jitter(width = 0.07, alpha = 0.45, size = 1.5, color = "#3BAA9A") +
  coord_flip() +
  scale_y_log10(
    name = expression(paste("Dosage [ug/L]")),
    labels = scales::label_number()
  ) +
  labs(
    x = NULL,
    caption = paste0("Median = ", signif(med, 3),
      ", Q1 = ", signif(q1, 3),
      ", Q3 = ", signif(q3, 3))
  ) +
  theme_classic(base_size = 13) +
  theme(
    plot.caption.position = "plot",
    plot.caption = element_text(hjust = 1, face = "italic"),
    axis.title.y = element_text(face = "bold"),
    axis.text.y  = element_blank(),
    axis.ticks.y = element_blank()
  )
p_log


```


```{r}
## Moderate by duration of pharmaceutical (lnRR)

# Create dataframe for model with consistent duration units
data_duration <- data %>% 
  filter(!is.na(duration), duration != "not reported") %>%
  mutate(duration = as.numeric(duration),
         duration_unit = as.character(duration_unit),
           duration_unit_consistent = case_when(
          duration_unit == "minutes" ~ "hours",
          duration_unit == "days" ~ "hours",
          duration_unit == "weeks" ~ "hours",
           TRUE ~ duration_unit),
 duration_convert = case_when(
    duration_unit == "minutes" ~ duration/ 60, 
    duration_unit == "days" ~ duration*24, 
    duration_unit == "weeks" ~ duration*168,
    TRUE ~ duration))

summary(data_duration$duration_convert)
```


```{r}
# Create the violin plot

med_duration <- median(data_duration$duration_convert, na.rm = TRUE)
q1_duration  <- quantile(data_duration$duration_convert, 0.25, na.rm = TRUE)
q3_duration  <- quantile(data_duration$duration_convert, 0.75, na.rm = TRUE)


duration_violin_plot <- ggplot(data_duration, aes(y = duration_unit_consistent, x = duration_convert)) +
  geom_violin(fill = RColorBrewer::brewer.pal(n = 8, name = "Set2")[1], alpha = 0.4, color = NA, trim = FALSE) +
  geom_boxplot(width = 0.1, fill = "white", color = RColorBrewer::brewer.pal(n = 8, name = "Set2")[2], outlier.shape = NA) +
  geom_jitter(width = 0.3, height = 0.09, color = RColorBrewer::brewer.pal(n = 8, name = "Set2")[1], alpha = 0.8) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold"),
        axis.text.x = element_text(color = "black"),
        axis.text.y = element_blank(),
        axis.ticks = element_line(color = "black"),
        plot.caption = element_text(size = 10, color = "gray10", face = "italic")) +
  labs(caption = "", y = "Duration [hours]")

print(duration_violin_plot)
```


```{r}
##Question: Does exposure duration influence the magnitude of effects on fish immunocompetence?

#Recompute V on the filtered data and use it
lnRRVCV_duration <- metafor::vcalc(
  vi = lnRRv, cluster = exposure_id, obs = assay_id,
  data = data_duration, rho = 0.5
)
lnRRVCV_duration <- lnRRVCV_duration + diag(1e-5, nrow(lnRRVCV_duration))

# Model duration (lnRR)
lnRR_mod_duration <- metafor::rma.mv(
  yi = lnRR, V = lnRRVCV_duration,
  mods = ~ duration_convert -1,
  random = list(~1 | study_id,
                                                 ~1 | assay_id,
                                                 ~1 | pharmaceutical,
                                                 ~1 | species_latin,
                                                 ~1 | phylogeny),
  method = "REML", test = "t",
  data = data_duration, sparse = TRUE, 
  R = list(phylogeny = phylo_matrix))

summary(lnRR_mod_duration)


duration_mod_lnRR_results <- mod_results(lnRR_mod_duration, mod = "duration_convert", data = data_duration, group = "study_id") 

r2_lnRR_duration <- r2_ml(lnRR_mod_duration, data_duration)
r2_lnRR_duration
```


```{r}
# Figure 5a)
## We illustrate the (a) moderating effects of dosage (ug/L, on a logarithmic scale) and (b) duration (hours) on the mean of immune response. The R2 values indicate the minimal variance explained by dosage and duration

dosage_bubble_plot.lnRR <- bubble_plot(dosage_mod_lnRR_results, mod = "log_dosage_convert_ugL", group = "study_id", x = "dosage_convert_ugL",
                                       y = "lnRR", est.lwd = 1, legend.pos = "bottom.right", k.pos = "bottom.left",
                                       ci.col = "red", pi.col = "black", est.col = "black", g = TRUE) + annotate(geom = "text",
                                                                                                                 x = 7, y = 5.8, label = paste0("italic(R)^{2} == ", round(r2_lnRR_dosage[1], 4)), color = "black",
                                                                                                                 parse = TRUE, size = 4)  + 
  ggtitle("") + 
  theme(plot.title = element_text(size = 18),
        legend.position = "none", axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 14), axis.text.x = element_text(size = 14)) +
  xlab("Dosage (log10 scale)")

dosage_bubble_plot.lnRR

# Figure 5b)
duration_bubble_plot.lnRR <- bubble_plot(duration_mod_lnRR_results, mod = "duration_convert", group = "study_id", x = "duration_convert",
                                         y = "lnRR", est.lwd = 1, legend.pos = "bottom.right", k.pos = "bottom.left",
                                         ci.col = "red", pi.col = "black", est.col = "black", g = TRUE) +  annotate(geom = "text", x =2800, y =1.3, 
                                                                                                                    label = paste0("italic(R)^{2} == ", round(r2_lnRR_duration[1], 4)), color = "black",
                                                                                                                    parse = TRUE, size = 4)  + 
  ggtitle("") + 
  theme(plot.title = element_text(size = 18),
        legend.position = "none", axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 14), axis.text.x = element_text(size = 14)) +
  xlab("Duration (hours)")

duration_bubble_plot.lnRR
```



```{r}
### Question: Is the effect of pharmaceuticals on fish immunocompetence sex-dependent?
#moderate by sex
#Model lnRR

lnRR_mod_sex <- rma.mv(yi = lnRR,
                           V = lnRRVCV,
                           random = list(~1 | study_id,
                                                 ~1 | assay_id,
                                                 ~1 | pharmaceutical,
                                                 ~1 | species_latin,
                                                 ~1 | phylogeny),
                           mods = ~sex -1,
                           method = "REML",
                           test = "t", 
                           data = data,
                           sparse = T,
                           R = list(phylogeny = phylo_matrix))

# Summary results
summary(lnRR_mod_sex)

r2_ml(lnRR_mod_sex)

lnRR_sex_mod_results <- mod_results(lnRR_mod_sex, mod = "sex", data = data, group = "study_id")  

```

```{r}
#Figure
pal_sex <- c(
  "Not reported" = "#9FD5C0",  # light grey (neutral)
  "Mixed"        = "#8FBCE6",  # blue (same as WBC tone for consistency)
  "Male"         = "#F7C9A9"   # orange (balanced contrast)
)


sex_mod_orchard.lnRR <-
  orchaRd::orchard_plot(
    lnRR_mod_sex,
    group = "study_id",
    xlab  = "Log Response Ratio (lnRR)",
    mod   = "sex",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,
    branch.size = 1.2,
    twig.size   = 0.8
  ) +
  scale_fill_manual(values = pal_sex) +
  geom_vline(xintercept = 0, linetype = "dashed",
             color = "black", linewidth = 0.4) +
  theme_pub_large +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.y = element_text(face = "bold", color = "black")
  ) +
  labs(title = NULL)

# Slim summary layer
sex_mod_orchard.lnRR$layers[[4]]$geom_params$fatten    <- 1.7
sex_mod_orchard.lnRR$layers[[4]]$geom_params$linewidth <- 0.35

sex_mod_orchard.lnRR
```


```{r}
## Question: Is the effect of pharmaceuticals on fish immune competence age-dependent?
#moderate by age (lnRR)
## Recode age -> merge juvenile/embryo/larvae/eggs into "early_life_stage"
data <- data %>%
  mutate(
    age = tolower(str_trim(age)),
    age_recode = case_when(
      age %in% c("juvenile", "embryo", "larvae", "eggs") ~ "early_life_stage",
      age %in% c("adult", "not reported") ~ age,
      TRUE ~ "not reported"           # catch-all
    ),
    # choose reference level you prefer (here: "adult")
    age_recode = factor(age_recode, levels = c("adult","early_life_stage","not reported"))
  )


# Model
lnRR_mod_age <- rma.mv(yi = lnRR,
                       V = lnRRVCV,
                       random = list(~1 | study_id,
                                                 ~1 | assay_id,
                                                 ~1 | pharmaceutical,
                                                 ~1 | species_latin,
                                                 ~1 | phylogeny),
                       mods = ~age_recode -1,
                       method = "REML",
                       test = "t", 
                       data = data,
                       sparse = T,
                       R = list(phylogeny = phylo_matrix))

# Summary results
summary(lnRR_mod_age)

r2_ml(lnRR_mod_age)

lnRR_age_mod_results <- mod_results(lnRR_mod_age, mod = "age_recode", data = data, group = "study_id")  

```

```{r}
## Figure 
pal_age <- c(
  "Not reported"     = "#9FD5C0",  # neutral grey
  "Early_life_stage" = "#8FBCE6",  # blue
  "Adult"            = "#F7C9A9"   # orange
)

age_mod_orchard.lnRR <-
  orchaRd::orchard_plot(
    lnRR_mod_age,
    group = "study_id",
    xlab  = "Log Response Ratio (lnRR)",
    mod   = "age_recode",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,
    branch.size = 1.2,
    twig.size   = 0.8
  ) +
  scale_fill_manual(values = pal_age) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", linewidth = 0.4) +
  theme_pub_large +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.y = element_text(face = "bold", color = "black")
  ) +
  labs(title = NULL)

# Shrink summary bubble and slim summary CI line (if layer 4 is summary)
age_mod_orchard.lnRR$layers[[4]]$geom_params$fatten    <- 1.7
age_mod_orchard.lnRR$layers[[4]]$geom_params$linewidth <- 0.35

age_mod_orchard.lnRR
```
