---
title: "lnRR"
author: "Gabriel Melhado"
date: "2025-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
pacman::p_load(devtools, tidyverse, metafor, patchwork, R.rsp, orchaRd, emmeans, ape, phytools, flextable, here, kableExtra, magrittr, metagear, rotl, clubSandwich, MuMIn, ggsankey, scales)
```

```{r}
# Load Data
data <- read.csv(here("data", "data_pharma_immune.csv"))

```

```{r}
## Calculate effect sizes and sampling variances
# Make sure all data is numeric 
data <- data  %>%
  mutate(
    treatment_mean = as.numeric(treatment_mean),
    treatment_sd = as.numeric(treatment_sd),
    treatment_n = as.numeric(treatment_n),
    control_mean = as.numeric(control_mean),
    control_sd = as.numeric(control_sd),
    control_n = as.numeric(control_n)
  )

# Calculate log response ratio (lnRR)
lnRR <- escalc(measure = "ROM", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)


# Calculate log coefficient variation ratio (lnCVR)
lnCVR <- escalc(measure = "CVR", 
                m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
                m2i = control_mean, sd2i = control_sd, n2i = control_n, 
                data = data)

# Calculate the standardised mean difference for sensitivity analysis
SMD <- escalc(measure = "SMD", 
              m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
              m2i = control_mean, sd2i = control_sd, n2i = control_n, 
              data = data)

# Calculate log variation ratio (lnVR)
lnVR <- escalc(measure = "VR", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)

# Summary statistics of sampling variances
sampling_variance_summaries <- list(
  lnRR = summary(lnRR$vi),
  lnCVR = summary(lnCVR$vi),
  SMD = summary(SMD$vi),
  VR = summary(lnVR$vi)
)

# Calculate precision for each effect size estimate with checks
lnRR$precision <- ifelse(lnRR$vi > 0, 1 / sqrt(lnRR$vi), NA)
lnCVR$precision <- ifelse(lnCVR$vi > 0, 1 / sqrt(lnCVR$vi), NA)
SMD$precision <- ifelse(SMD$vi > 0, 1 / sqrt(SMD$vi), NA)
lnVR$precision <- ifelse(lnVR$vi > 0, 1 / sqrt(lnVR$vi), NA)


# Merge the data
effect_size_metrics_set <- data.frame(
  lnRR = lnRR$yi, lnRRv = lnRR$vi, lnRR_precision = lnRR$precision,
  lnVR = lnVR$yi, lnVRv = lnVR$vi, lnVR_precision = lnVR$precision,
  lnCVR = lnCVR$yi, lnCVRv = lnCVR$vi, lnCVR_precision = lnCVR$precision,
  SMD = SMD$yi, SMDv = SMD$vi, SMD_precision = SMD$precision,
  control_imputed = data$control_sd, treatment_imputed = data$treatment_sd
)

# Bind the effect size metrics set to the main data
data <- cbind(data, effect_size_metrics_set)

#Flip the sign (change effect sizes direction)
data <- subset(data, orientation != 0) #Remove immune traits with orientation "0"
data$lnRR <- ifelse(data$orientation == "-1", -1 * data$lnRR, data$lnRR)


# Select specific columns including the new precision columns
effect_size_metrics_set_kable <- data[, which(colnames(data) %in% c(
  "study_id","assay_id", "species_english", "pharmaceutical", "immune_trait_category",
  "lnRR", "lnRRv", "lnRR_precision", 
  "lnCVR", "lnCVRv", "lnCVR_precision", 
  "lnVR", "lnVRv", "lnVR_precision", 
  "SMD", "SMDv", "SMD_precision", 
  "control_imputed", "treatment_imputed"
))] %>% dfround(digits = 3)

# Table of the effect sizes
kable(effect_size_metrics_set_kable, "html") %>%
  kable_styling("bordered", position = "left") %>%
  scroll_box(width = "250%", height = "800px")

# Figure 1
# Plot the distribution of effect size estimates (lnRR)
lnRR_dist_plot <- effect_size_metrics_set_kable %>%
  ggplot(aes(lnRR)) +
  geom_histogram(fill = RColorBrewer::brewer.pal(n = 8, name = "Set2")[2], col = "black", binwidth = 0.1, alpha = 0.4) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        axis.ticks = element_line(color = "black"),
        plot.caption = element_text(size = 10, color = "gray10", face = "italic")) +
  labs(caption = "Distribution of Effect Size Estimates (lnRR)",
       x = "lnRR",
       y = "Frequency")

print(lnRR_dist_plot)
```

```{r}
## Dependent effect size estimates
# Create phylogenetic tree

data <- as.data.frame(data)

data$species_latin = as.factor(data$species_latin)

taxa <- tnrs_match_names(names = levels(data$species_latin), context = "Animals")  # Match species names to the Open Tree of Life taxonomy

kable(taxa)  # Display matched species, ensuring each species has a unique match in the Open Tree of Life

taxa$unique_name <- gsub(" ", "_", taxa$unique_name)  # Replace spaces in species names with underscores

phylo_tree <- tol_induced_subtree(ott_ids = taxa$ott_id, label_format = "name")  # Generate a phylogenetic tree based on the Open Tree of Life taxonomy

ott_in_tree <- ott_id(taxa)[is_in_tree(ott_id(taxa))]  # Ensure all identifiers are present in the taxonomy

phylo_tree <- tol_induced_subtree(ott_ids = ott_in_tree)  # Generate a phylogenetic tree including all species present in the taxonomy

is.binary(phylo_tree)  # Check if tree is binary 


# Plot for the phylogenetic tree
plot(phylo_tree,
     cex= 1, #font size
     label.offset =.1,
     no.margin = TRUE)

# Compute branch length
phylo_branched <- compute.brlen(phylo_tree, method = "Grafen", power = 1)  # compute branch lengths using Grafen's method

phylo_branched$tip.label <- strip_ott_ids(phylo_branched$tip.label, remove_underscores = FALSE)  # remove ott ID from species name to match it to the data set

phylo_matrix <- vcv(phylo_branched, cor = T)  # Generate variance covariance matrix to correlate species relatedness 

data <- as.data.frame(data)
data <- data[, !duplicated(names(data))]

# Convert species_latin to lowercase
data <- mutate(data, search_string = tolower(species_latin))

data <- left_join(data, select(taxa, search_string, unique_name, ott_id), by = "search_string")  # Join data sets

data <- data[data$unique_name %in% phylo_branched$tip.label, ]  # Check that species names are well matched with the phylogenetic tree


data$phylogeny <- data$unique_name  # Rename 'unique_name' to 'phylogeny' for the models

```


```{r}
## Variance covariance matrices
# To account for the dependency of effect sizes estimates due to being in the same exposure group (cohort) we constructed a series of vcv matrices.

#------------------------------lnRR------------------------------#
data<- data[!is.na(data$lnRRv),] 
lnRRVCV <- metafor::vcalc(vi = lnRRv, cluster = exposure_id, obs = assay_id, data = data, rho = 0.5)
lnRRVCV <- lnRRVCV + diag(1e-5, nrow(lnRRVCV))

```

```{r}
### Selection of random-effect structure
## Null model with no random effects (lnRR)
# fit a null model as default model
null_mod_lnRR <- rma.mv(yi = lnRR, 
                        V = lnRRVCV, 
                        method = "ML", 
                        test = "t", 
                        data = data, 
                        sparse = TRUE ) # Use ML to compare information criteria

summary(null_mod_lnRR)
```

```{r}
## Add *assay_id* as a random effect and compare with the null model (lnRR)
mod_lnRR.assay_id <- rma.mv(yi = lnRR, 
                            V = lnRRVCV,
                            random =  ~1 | assay_id,
                            method = "ML", 
                            test = "t", 
                            data = data, 
                            sparse = T)

summary(mod_lnRR.assay_id)

anova(null_mod_lnRR,mod_lnRR.assay_id)
```

```{r}
## Add *study_id* as a random effect to the null model and compare with the assay model (lnRR)
mod_lnRR.assay_id.study_id <- rma.mv(yi = lnRR,
                                     V = lnRRVCV,
                                     random = list(~1 | study_id, 
                                                   ~1 | assay_id),
                                     method = "ML",
                                     test = "t", 
                                     data = data, 
                                     sparse = T)

summary(mod_lnRR.assay_id.study_id)

anova(mod_lnRR.assay_id,mod_lnRR.assay_id.study_id)

```

```{r}
## Add *exposure_id* as a random effect to the above model (that used *assay_id* and *study_id* as random effets) (lnRR)
mod_lnRR.assay_id.study_id.exp_id <- rma.mv(yi = lnRR,
                                            V = lnRRVCV,
                                            random = list(~1 | study_id,
                                                          ~1 | exposure_id,
                                                          ~1 | assay_id),
                                            method = "ML",
                                            test = "t", 
                                            data = data,
                                            sparse = T)

summary(mod_lnRR.assay_id.study_id.exp_id)

anova(mod_lnRR.assay_id.study_id,mod_lnRR.assay_id.study_id.exp_id)
```

```{r}
## Add *phylogeny* as a random effect to the better model (that used *assay_id* and *study_id* as random effects) (lnRR)
mod_lnRR.assay_id.study_id.species.phylogeny <- rma.mv(yi = lnRR,
                                                       V = lnRRVCV,
                                                       random = list(~1 | study_id,
                                                                     ~1 | assay_id,
                                                                  
~1 | phylogeny),
                                                       method = "ML",
                                                       test = "t", 
                                                       data = data, 
                                                       sparse = T,
                                                       R = list(phylogeny = phylo_matrix))

summary(mod_lnRR.assay_id.study_id.species.phylogeny)

anova(mod_lnRR.assay_id.study_id,mod_lnRR.assay_id.study_id.species.phylogeny)
```


```{r}
## Add *pharmaceutical_class* as a random effect to the better model (that used *assay_id* and *study_id* as random effects) (lnRR)
mod_lnRR.assay_id.study_id.pharmaceutical_class <- rma.mv(yi = lnRR,
                                                       V = lnRRVCV,
                                                       random = list(~1 | study_id,
                                                                     ~1 | assay_id,
                                                                     ~1 | pharmaceutical_class),
                                                       method = "ML",
                                                       test = "t", 
                                                       data = data, 
                                                       sparse = T)

summary(mod_lnRR.assay_id.study_id.pharmaceutical_class)

anova(mod_lnRR.assay_id.study_id, mod_lnRR.assay_id.study_id.pharmaceutical_class)

i2_ml(mod_lnRR.assay_id.study_id.pharmaceutical_class)

```


```{r}
### Question: What's the impact of pharmaceutical exposure on immunocompetence of fish?

## Intercept only meta-analysis models
#Intercept only model (lnRR)

lnRR_intercept_only <- rma.mv(yi = lnRR,
                              V = lnRRVCV,
                              random = list(~1 | study_id,
                                            ~1 | assay_id,
                                            ~1 | pharmaceutical_class,
                                            ~1 | species_latin,
                                            ~1 | phylogeny),
                              method = "REML",
                              test = "t", 
                              data = data,
                              sparse = T,
                              R = list(phylogeny = phylo_matrix))

# Summary statistics 
summary(lnRR_intercept_only)

mod_results(lnRR_intercept_only, mod = "1", data = data, group = "study_id")  # For prediction intervals

i2_ml(lnRR_intercept_only)

# Given point estimate of lnRR
lnRR_point <- lnRR_intercept_only$b[[1]]

# Calculate the percentage change
lnRR_percentage_change <- (1 - exp(lnRR_point)) * 100
lnRR_percentage_change
```

```{r}
## Figure 2
#Impacts of pharmaceutical exposure on fish immune response. The model estimates the average effects of pharmaceutical exposure on fish immune responses. (a) shows the mean difference between control and treatment groups on a logarithmic scale, where negative values indicate a weak immune response, and positive values indicate a strong immune response.Shorter whiskers represent 95% confidence intervals, while longer whiskers indicate 95% prediction intervals. 'k' represents the number of effect sizes, and the number of studies is in brackets. Each circle corresponds to an effect size, with its size scaled by precision (the inverse of the sampling error variance)

# Figure 2
# Create the plot
intercept_only.lnRR_orchard <- orchaRd::orchard_plot(lnRR_intercept_only,
                                                     group = "study_id",
                                                     xlab = "lnRR",
                                                     g = TRUE,
                                                     k.pos = "right",
                                                     colour = FALSE,
                                                     fill = TRUE,  
                                                     trunk.size = 0.8, 
                                                     legend.pos = "none",
                                                     branch.size = 1.5,
                                                     twig.size = 0.5) +
  scale_fill_manual(values = RColorBrewer::brewer.pal(8, "Dark2")[1]) +
  scale_x_discrete(labels = c("Model estimates")) +
  theme(
    panel.grid = element_blank(),      # removes all gridlines
    panel.grid.major = element_blank(),# removes major gridlines 
    panel.grid.minor = element_blank() # removes minor gridlines
  )

# Display the plot
intercept_only.lnRR_orchard

```


```{r}
#### Question: Do immune traits differ in their responses to pharmaceutical exposure?

## Single moderator meta-regression
# Immune categories (lnRR)*

lnRR_mod_immune_category_high <- rma.mv(yi = lnRR,
                                   V = lnRRVCV,
                                   random = list(~1 | study_id,
                                                 ~1 | assay_id,
                                                 ~1 | pharmaceutical_class,
                                                 ~1 | species_latin,
                                                 ~1 | phylogeny),
                                   mods = ~immune_category_high -1,
                                   method = "REML",
                                   test = "t", 
                                   data = data,
                                   sparse = T,
                                   R = list(phylogeny = phylo_matrix))


# Summary results
summary(lnRR_mod_immune_category_high)

mod_results(lnRR_mod_immune_category_high, mod = "immune_category_high", data = data, group = "study_id")  

r2_ml(lnRR_mod_immune_category_high)

# Extract named estimates from the model
estimates_immune_category_high <- lnRR_mod_immune_category_high$b

# Compute % change for all estimates
lnRR_percentage_change <- (1 - exp(estimates_immune_category_high)) * 100

# View results
lnRR_percentage_change

```


```{r}
# Figure 3
pal_pastel <- c("#BFD3E6", "#F7C9A9", "#D1B3E0", "#B9E3C6")  # pastel set

immune_category_high_mod_orchard.lnRR <-
  orchaRd::orchard_plot(
    lnRR_mod_immune_category_high,
    group = "study_id",
    xlab  = "lnRR",
    mod   = "immune_category_high",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,   # summary CI line
    branch.size = 1.2,   # study CI lines
    twig.size   = 0.8    # study dots
  ) +
  scale_fill_manual(values = pal_pastel) +
  # Clean, axis-only look
  theme_classic(base_size = 11) +
  theme(
    axis.text.y = element_text(angle = 0),
    legend.position = "none"
  ) +
  # Reference at no effect
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(title = NULL) +
  patchwork::plot_annotation(tag_levels = "A")

# shrink the summary bubble and the PI line on the summary layer
immune_category_high_mod_orchard.lnRR$layers[[4]]$geom_params$fatten    <- 1.7  # default is 4
immune_category_high_mod_orchard.lnRR$layers[[4]]$geom_params$linewidth <- 0.35 # ggplot ≥3.4

immune_category_high_mod_orchard.lnRR

```


```{r}
## Question: Do pharmaceutical vary in their effects on fish immunocompetence?
#Moderate by pharmaceutical_class (lnRR)
lnRR_mod_pharmaceutical_class <- rma.mv(yi = lnRR,
                                  V = lnRRVCV,
                                  random = list(~1 | study_id,
                                                 ~1 | assay_id,
                                                 ~1 | pharmaceutical_class,
                                                 ~1 | species_latin,
                                                 ~1 | phylogeny),
                                  mods = ~pharmaceutical_class -1,
                                  method = "REML",
                                  test = "t", 
                                  data = data,
                                  sparse = T,
                                  R = list(phylogeny = phylo_matrix))

# Summary results
summary(lnRR_mod_pharmaceutical_class)

lnRR_pharmaceutical_class_mod_results <- mod_results(lnRR_mod_pharmaceutical_class, mod = "pharmaceutical_class", data = data, group = "study_id") 

r2_ml(lnRR_mod_pharmaceutical_class)

```

```{r}
### *Figure 4*
#The moderating effects of pharmaceutical_class on (A) response magnitude 
# Figure 4
pharmaceutical_class_mod_orchard.lnRR <- orchaRd::orchard_plot(lnRR_mod_pharmaceutical_class,
                                                        group = "study_id", 
                                                        xlab = "lnRR",
                                                        
                                                        mod = "pharmaceutical_class",
                                                        g = TRUE,
                                                        k.pos = "right",
                                                        colour = FALSE,
                                                        fill = TRUE,  
                                                        legend.pos = "none",
                                                        trunk.size = 0.8, 
                                                        branch.size = 1.2,
                                                        twig.size = 0.8) +
  scale_fill_viridis_d(option = "plasma") +  # Ensures enough colors
  theme(axis.text.y = element_text(angle = 0)) +  # Make y-axis labels straight
  plot_annotation(tag_levels = "A")

pharmaceutical_class_mod_orchard.lnRR

```

```{r}
# 1) Soft pastel palette
pal_pastel <- c("#BFD3E6", "#F7C9A9", "#D1B3E0", "#B9E3C6")

# 2) Build the orchard with lighter geometry
pharmaceutical_class_mod_orchard.lnRR <-
  orchaRd::orchard_plot(
    lnRR_mod_pharmaceutical_class,
    group = "study_id",
    xlab  = "lnRR",
    mod   = "pharmaceutical_class",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,   # summary CI line
    branch.size = 1.2,   # study CI lines
    twig.size   = 0.8    # study dots
  ) +
  # Pastel colours
  scale_fill_manual(values = pal_pastel) +
  # Axis-only look + zero line
  theme_classic(base_size = 11) +
  theme(
    axis.text.y = element_text(angle = 0),
    legend.position = "none"
  ) +
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.4, alpha = 0.7)

# 3) Shrink the big summary bubble (layer [[4]] is the summary pointrange)
pharmaceutical_class_mod_orchard.lnRR$layers[[4]]$geom_params$fatten    <- 1.7 # default ~4

# 5) (Optional) slim the CI lines (layers [[3]] & [[4]])
pharmaceutical_class_mod_orchard.lnRR$layers[[3]]$geom_params$linewidth <- 0.35
pharmaceutical_class_mod_orchard.lnRR$layers[[4]]$geom_params$linewidth <- 0.35

pharmaceutical_class_mod_orchard.lnRR

##ggsave("fig_class_orchard.png", combined_plot_age, width = 300, height = 120, units = "mm", dpi = 300, bg = "white")

# Combine plots side by side and add labels (a) and (b)
#combined_plot_sex <- sex_mod_orchard.lnRR + lnVR_mod_sex_figure + plot_annotation(tag_levels = 'a') combined_plot_sex

# Combine plots side by side and label them (c) and (d)
#combined_plot_age <- age_mod_orchard.lnRR + age_mod_orchard.lnVR + plot_annotation(tag_levels = list(c("c", "d")))

```

```{r}
# Step 1: Create a data frame with one row per pharmaceutical_class
pharma_levels_lnRR <- data.frame(pharmaceutical_class = sort(unique(data$pharmaceutical_class)))

# Step 2: Create the model matrix
X_pharma_lnRR <- model.matrix(~ pharmaceutical_class - 1, data = pharma_levels_lnRR)

# Step 3: Get predictions from the model
pharma_preds_lnRR <- predict(lnRR_mod_pharmaceutical_class, newmods = X_pharma_lnRR, level = 95)

# Step 4: Build the plot data frame
pharma_plot_data_lnRR <- data.frame(
  pharmaceutical_class = pharma_levels_lnRR$pharmaceutical_class,
  estimate = pharma_preds_lnRR$pred,
  ci.lb = pharma_preds_lnRR$ci.lb,
  ci.ub = pharma_preds_lnRR$ci.ub
)

# Step 5: Order the classes by effect size
pharma_plot_data_lnRR <- pharma_plot_data_lnRR %>%
  arrange(estimate) %>%
  mutate(pharmaceutical_class = factor(pharmaceutical_class, levels = pharmaceutical_class))

# Step 6: Plot
ggplot(pharma_plot_data_lnRR, aes(x = estimate, y = pharmaceutical_class)) +
  geom_point(color = "black", size = 2) +
  geom_errorbarh(aes(xmin = ci.lb, xmax = ci.ub), color = "black", height = 0.2) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "lnRR", y = NULL) +
  theme_minimal() +
  theme(axis.text.y = element_text(angle = 0, size = 10))

```

```{r}
# 1. Count number of studies (rows) per combination
plot_data <- data %>%
  count(pharmaceutical_class, immune_category_high)

# 2. Plot
frequency_cross_tabulation <- ggplot(plot_data, aes(x = pharmaceutical_class, y = n, fill = immune_category_high)) +
  geom_bar(stat = "identity", position = "dodge") +  # dodge = side-by-side bars
  labs(
    x = "Pharmaceutical Class",
    y = "Effect",
    fill = "Immune Response Category"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)  # Rotate x-axis labels if long
  )


frequency_cross_tabulation
```


```{r}
### *Moderate by concentration of pharmaceutical (lnRR)*
# Create dataframe for model with consistent dosage units
unique_dosage_units <- unique(data$dosage_unit)
print(unique_dosage_units)

data_dosage <- data %>% 
  mutate(dosage = as.numeric(dosage),
         dosage_unit = as.character(dosage_unit),
         dosage_unit_consistent = case_when(
           dosage_unit == "mg/L" ~ "ug/L", 
           dosage_unit == "ng/L" ~ "ug/L",
           dosage_unit == "ppm" ~ "ug/L", 
           TRUE ~ dosage_unit),
         dosage_convert_ugL = case_when(
           dosage_unit == "mg/L" ~ dosage * 1000,
           dosage_unit == "ng/L" ~ dosage / 1000,
           dosage_unit == "ppm" ~ dosage*1000, 
           TRUE ~ dosage)) %>% 
   filter(!is.na(dosage_convert_ugL)) %>% 
    mutate(log_dosage_convert_ugL = log(dosage_convert_ugL)) 

#Summary table for the dosage converted
summary_data_dosage <- summary(data_dosage$dosage_convert_ugL)
```


```{r}
# Recalculate the VCV matrix based on the new data frame 
lnRRVCV_dosage <- metafor::vcalc(vi = lnRRv, cluster = exposure_id, obs = assay_id, data = data_dosage, rho = 0.5)

# Model (lnRR)
lnRR_mod_dosage <- rma.mv(yi = lnRR,
                          V = lnRRVCV,
                          random = list(~1 | study_id,
                                        ~1 | assay_id),
                                        
                          mods = ~log_dosage_convert_ugL - 1,
                          method = "REML",
                          test = "t", 
                          data = data_dosage,
                          sparse = T)

# Summary results 
summary(lnRR_mod_dosage)

dosage_mod_lnRR_results <- mod_results(lnRR_mod_dosage, 
        mod = "log_dosage_convert_ugL",
        data = data_dosage, 
        group = "study_id")  

r2_lnRR_dosage <- r2_ml(lnRR_mod_dosage, data_dosage)
r2_lnRR_dosage

```


```{r}
#create the violin plot
med <- median(data_dosage$dosage_convert_ugL, na.rm = TRUE)
q1  <- quantile(data_dosage$dosage_convert_ugL, 0.25, na.rm = TRUE)
q3  <- quantile(data_dosage$dosage_convert_ugL, 0.75, na.rm = TRUE)


# Filter the data for dosage_convert_ugL less than 1000
filtered_data_dosage <- data_dosage %>%
  filter(dosage_convert_ugL < 1000)

p_log <- ggplot(filtered_data_dosage, aes(x = "", y = dosage_convert_ugL)) +
  geom_violin(fill = "#8ED7C6", alpha = 0.35, color = NA, width = 1) +
  geom_boxplot(width = 0.12, outlier.shape = NA,
               color = "#F28E2B", fill = NA, linewidth = 0.9) +
  geom_jitter(width = 0.07, alpha = 0.45, size = 1.5, color = "#3BAA9A") +
  coord_flip() +
  scale_y_log10(
    name = expression(paste("Dosage [ug/L]")),
    labels = scales::label_number()
  ) +
  labs(
    x = NULL,
    caption = paste0("Median = ", signif(med, 3),
      ", Q1 = ", signif(q1, 3),
      ", Q3 = ", signif(q3, 3))
  ) +
  theme_classic(base_size = 13) +
  theme(
    plot.caption.position = "plot",
    plot.caption = element_text(hjust = 1, face = "italic"),
    axis.title.y = element_text(face = "bold"),
    axis.text.y  = element_blank(),
    axis.ticks.y = element_blank()
  )
p_log


```


```{r}
### *Moderate by duration of pharmaceutical (lnRR)*
# Create dataframe for model with consistent duration units
data_duration <- data %>% 
  filter(!is.na(duration), duration != "not reported") %>%
  mutate(duration = as.numeric(duration),
         duration_unit = as.character(duration_unit),
           duration_unit_consistent = case_when(
          duration_unit == "minutes" ~ "hours",
          duration_unit == "days" ~ "hours",
          duration_unit == "weeks" ~ "hours",
           TRUE ~ duration_unit),
 duration_convert = case_when(
    duration_unit == "minutes" ~ duration/ 60, 
    duration_unit == "days" ~ duration*24, 
    duration_unit == "weeks" ~ duration*168,
    TRUE ~ duration))

summary(data_duration$duration_convert)
```


```{r}
# Create the violin plot

med_duration <- median(data_duration$duration_convert, na.rm = TRUE)
q1_duration  <- quantile(data_duration$duration_convert, 0.25, na.rm = TRUE)
q3_duration  <- quantile(data_duration$duration_convert, 0.75, na.rm = TRUE)


duration_violin_plot <- ggplot(data_duration, aes(y = duration_unit_consistent, x = duration_convert)) +
  geom_violin(fill = RColorBrewer::brewer.pal(n = 8, name = "Set2")[1], alpha = 0.4, color = NA, trim = FALSE) +
  geom_boxplot(width = 0.1, fill = "white", color = RColorBrewer::brewer.pal(n = 8, name = "Set2")[2], outlier.shape = NA) +
  geom_jitter(width = 0.3, height = 0.09, color = RColorBrewer::brewer.pal(n = 8, name = "Set2")[1], alpha = 0.8) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold"),
        axis.text.x = element_text(color = "black"),
        axis.text.y = element_blank(),
        axis.ticks = element_line(color = "black"),
        plot.caption = element_text(size = 10, color = "gray10", face = "italic")) +
  labs(caption = "", y = "Duration [hours]")

print(duration_violin_plot)
```


```{r}
## 4) Recompute V on the filtered data and use it
lnRRVCV_duration <- metafor::vcalc(
  vi = lnRRv, cluster = exposure_id, obs = assay_id,
  data = data_duration, rho = 0.5
)
lnRRVCV_duration <- lnRRVCV_duration + diag(1e-5, nrow(lnRRVCV_duration))

## 5) Fit the model (note the explicit intercept)
lnRR_mod_duration <- metafor::rma.mv(
  yi = lnRR, V = lnRRVCV_duration,
  mods = ~ duration_convert -1,
  random = list(~1 | study_id, ~1 | assay_id),
  method = "REML", test = "t",
  data = data_duration, sparse = TRUE
)
summary(lnRR_mod_duration)


duration_mod_lnRR_results <- mod_results(lnRR_mod_duration, mod = "duration_convert", data = data_duration, group = "study_id") 

r2_lnRR_duration <- r2_ml(lnRR_mod_duration, data_duration)
r2_lnRR_duration
```


```{r}
# Figure 5a)
dosage_bubble_plot.lnRR <- bubble_plot(dosage_mod_lnRR_results, mod = "log_dosage_convert_ugL", group = "study_id", x = "dosage_convert_ugL",
                                       y = "lnRR", est.lwd = 1, legend.pos = "bottom.right", k.pos = "bottom.left",
                                       ci.col = "red", pi.col = "black", est.col = "black", g = TRUE) + annotate(geom = "text",
                                                                                                                 x = 7, y = 5.8, label = paste0("italic(R)^{2} == ", round(r2_lnRR_dosage[1], 4)), color = "black",
                                                                                                                 parse = TRUE, size = 4)  + 
  ggtitle("") + 
  theme(plot.title = element_text(size = 18),
        legend.position = "none", axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 14), axis.text.x = element_text(size = 14)) +
  xlab("Dosage (log10 scale)")

dosage_bubble_plot.lnRR

# Figure 5b)
duration_bubble_plot.lnRR <- bubble_plot(duration_mod_lnRR_results, mod = "duration_convert", group = "study_id", x = "duration_convert",
                                         y = "lnRR", est.lwd = 1, legend.pos = "bottom.right", k.pos = "bottom.left",
                                         ci.col = "red", pi.col = "black", est.col = "black", g = TRUE) +  annotate(geom = "text", x =2800, y =1.3, 
                                                                                                                    label = paste0("italic(R)^{2} == ", round(r2_lnRR_duration[1], 4)), color = "black",
                                                                                                                    parse = TRUE, size = 4)  + 
  ggtitle("") + 
  theme(plot.title = element_text(size = 18),
        legend.position = "none", axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 14), axis.text.x = element_text(size = 14)) +
  xlab("Duration (hours)")

duration_bubble_plot.lnRR
```

```{r}
# Figure 5a) Dose–response on lnRR
dosage_bubble_plot.lnRR <- bubble_plot(
  dosage_mod_lnRR_results,
  mod = "dosage_convert_ugL",
  group = "study_id",
  x = "dosage_convert_ugL",
  y = "lnRR",
  est.lwd = 1,
  legend.pos = "bottom.right",
  k.pos = "bottom.left",
  ci.col = "red",
  pi.col = "black",
  est.col = "black",
  g = TRUE
) +
  # Add R2 annotation
  annotate(
    geom = "text",
    x = 7, y = 5.8,
    label = paste0("italic(R)^{2} == ", round(r2_lnRR_dosage[1], 4)),
    color = "black",
    parse = TRUE, size = 4
  ) +
  # Axis labels with units and log scale notation
  xlab(expression(paste("Dosage (", mu, "g/L"))) +
  ylab("lnRR") +
  ggtitle("") +
  # Reference line at no effect
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.4, alpha = 0.7) +
  # Clean style
  theme_classic(base_size = 14) +
  theme(
    plot.title   = element_text(size = 18),
    legend.position = "none",
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    axis.text.x  = element_text(size = 14),
    axis.text.y  = element_text(size = 14)
  )

dosage_bubble_plot.lnRR

```


```{r}
#Moderate by phylogeny
#Model lnRR
# Model
lnRR_mod_phylogeny <- rma.mv(yi = lnRR,
                           V = lnRRVCV,
                           random = list(~1 | study_id,
                                         ~1 | assay_id
                           ),
                           mods = ~phylogeny -1,
                           method = "REML",
                           test = "t", 
                           data = data,
                           sparse = T)

# Summary results
summary(lnRR_mod_phylogeny)

r2_ml(lnRR_mod_phylogeny)


lnRR_phylogeny_mod_results <- mod_results(lnRR_mod_phylogeny, mod = "phylogeny", data = data, group = "study_id")  

```

```{r}
# Figure 6
phylogeny_mod_orchard.lnRR <- orchaRd::orchard_plot(lnRR_mod_phylogeny,
                                                      group = "study_id", 
                                                      xlab = "lnRR",
                                                      
                                                      mod = "phylogeny",
                                                      g = TRUE,
                                                      k.pos = "right",
                                                      colour = FALSE,
                                                      fill = TRUE,  
                                                      legend.pos = "none",
                                                      trunk.size = 0.8, 
                                                      branch.size = 1.5,
                                                      twig.size = 0.8) +
  scale_fill_viridis_d(option = "plasma") +  # Ensures enough colors
  theme(axis.text.y = element_text(angle = 0)) +  # Make y-axis labels straight
  plot_annotation(tag_levels = "A")

print(phylogeny_mod_orchard.lnRR)

```


```{r}
#moderate by sex
#lnRR
# Model
lnRR_mod_sex <- rma.mv(yi = lnRR,
                           V = lnRRVCV,
                           random = list(~1 | study_id,
                                         ~1 | assay_id
                           ),
                           mods = ~sex -1,
                           method = "REML",
                           test = "t", 
                           data = data,
                           sparse = T)

# Summary results
summary(lnRR_mod_sex)

r2_ml(lnRR_mod_sex)

lnRR_sex_mod_results <- mod_results(lnRR_mod_sex, mod = "sex", data = data, group = "study_id")  

```
```{r}
pal_pastel <- c("#BFD3E6", "#F7C9A9", "#D1B3E0", "#B9E3C6")  # soft pastel set

sex_mod_orchard.lnRR <-
  orchaRd::orchard_plot(
    lnRR_mod_sex,
    group = "study_id",
    xlab  = "lnRR",
    mod   = "sex",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,   # thinner summary CI line
    branch.size = 1.2,   # thinner study CI lines
    twig.size   = 0.8    # smaller study dots
  ) +
  scale_fill_manual(values = pal_pastel) +    # pastel palette
  # Clean, axis-only look
  theme_classic(base_size = 11) +
  theme(
    axis.text.y = element_text(angle = 0),
    legend.position = "none"
  ) +
  # Reference at no effect
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(title = NULL) +
  patchwork::plot_annotation(tag_levels = "A")  # if you’re using patchwork

# shrink the summary bubble and the PI line on the summary layer
sex_mod_orchard.lnRR$layers[[4]]$geom_params$fatten    <- 1.7  # default is 4
sex_mod_orchard.lnRR$layers[[4]]$geom_params$linewidth <- 0.35 # ggplot ≥3.4

sex_mod_orchard.lnRR
```


```{r}
#moderate by age (lnRR)
## 1) Recode age -> merge juvenile/embryo/larvae/eggs into "early_life_stage"
data <- data %>%
  mutate(
    age = tolower(str_trim(age)),
    age_recode = case_when(
      age %in% c("juvenile", "embryo", "larvae", "eggs") ~ "early_life_stage",
      age %in% c("adult", "not reported") ~ age,
      TRUE ~ "not reported"           # catch-all
    ),
    # choose reference level you prefer (here: "adult")
    age_recode = factor(age_recode, levels = c("adult","early_life_stage","not reported"))
  )


# Model
lnRR_mod_age <- rma.mv(yi = lnRR,
                       V = lnRRVCV,
                       random = list(~1 | study_id,
                                     ~1 | assay_id
                       ),
                       mods = ~age_recode -1,
                       method = "REML",
                       test = "t", 
                       data = data,
                       sparse = T)

# Summary results
summary(lnRR_mod_age)

r2_ml(lnRR_mod_age)

lnRR_age_mod_results <- mod_results(lnRR_mod_age, mod = "age_recode", data = data, group = "study_id")  

```

```{r}
age_mod_orchard.lnRR <-
  orchaRd::orchard_plot(
    lnRR_mod_age,
    group = "study_id",
    xlab  = "lnRR",
    mod   = "age_recode",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,   # thinner summary CI line
    branch.size = 1.2,   # thinner study CI lines
    twig.size   = 0.8    # smaller study dots
  ) +
  scale_fill_manual(values = pal_pastel) +    # pastel palette
  # Clean, axis-only look
  theme_classic(base_size = 11) +
  theme(
    axis.text.y = element_text(angle = 0),
    legend.position = "none"
  ) +
  # Reference at no effect
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(title = NULL) +
  patchwork::plot_annotation(tag_levels = "A")  # if you’re using patchwork

# shrink the summary bubble and the PI line on the summary layer
age_mod_orchard.lnRR$layers[[4]]$geom_params$fatten    <- 1.7  # default is 4
age_mod_orchard.lnRR$layers[[4]]$geom_params$linewidth <- 0.35 # ggplot ≥3.4

age_mod_orchard.lnRR
```


```{r}
# **Model selection and multi-model inference**
## *lnRR model selection and multi-model inference*

# Create a data frame with only the required columns
dosage_duration_set <- data.frame(
  dosage_convert_ugL = data_dosage$dosage_convert_ugL,
  duration_convert = data_duration$duration_convert
)

# Bind these columns to `data`
data <- cbind(data, dosage_duration_set)


#Model
mlmr.full.lnRR <- rma.mv(yi = lnRR, 
                         V = lnRRVCV, 
                         random = list(~1 | study_id,
                                       ~1 | assay_id),
                         mods = ~ immune_category_high + pharmaceutical_class + phylogeny + 
        age_recode + sex + dosage_convert_ugL + duration_convert,
                         method = "ML", 
                         test = "t", 
                         data = data, 
                         sparse = T)

r2_ml(mlmr.full.lnRR, data = data)

eval(metafor:::.MuMIn)  # use eval() function to extract helper functions from MuMIn and make them usable in metafor.

mlmr.dredge.lnRR <- dredge(mlmr.full.lnRR, beta = "none", evaluate = TRUE, rank = "AICc", trace=2)

# multimodel inference
summary(mlmr.full.lnRR)

# Select "best" models based on delta <= 2
best_model <- subset(mlmr.dredge.lnRR, delta <= 2, recalc.weights = FALSE)

# Display the results in a scrollable kable table
best_model %>%
  kable("html") %>%
  kable_styling("bordered", position = "left") %>%
  scroll_box(width = "100%", height = "800px")

# Relative importance values for the predictors
weights_lnRR <- sw(mlmr.dredge.lnRR)

# Convert the named vector into a data frame
weights_lnRR_df <- data.frame(
  predictor = names(weights_lnRR),  
  weight = as.numeric(weights_lnRR), 
  R2_marginal = c(0.106, 0.002, 0.0103, 0.011, 0.0215, 0.0092, 0.1269)
)

weights_lnRR

```

```{r}
### *Figure 6*
# lnRR model selection plot
weights_lnRR_plot <- weights_lnRR_df %>%
  ggplot(aes(x = reorder(predictor, weight), y = weight)) +
  geom_col(width = 0.8, alpha = 0.7) +
  coord_flip() + 
  scale_y_continuous(
    limits = c(0, 1.2),
    breaks = seq(0, 1, by = 0.2),
    expand = c(0, 0)
  ) +
  geom_text(aes(label = scales::percent(weight, accuracy = 1)), 
            size = 6, position = position_stack(vjust = 0.5), 
            color = "white", fontface = "bold") +
  geom_text(aes(y = 1.1,label = paste0("R2 = ", round(R2_marginal, 2))), 
            size = 4, 
            fontface = "italic", 
            color = "red") +
  theme_bw() +
  guides(size = "none") +
  theme(
    legend.position = "none",
    axis.text = element_text(color = "black"),
    axis.title = element_text(face = "bold", color = "black"),
    plot.caption = element_text(size = 10, color = "gray10", face = "italic")
  ) +
  labs(
    y = "Akaike Weights",
    x = "Moderators",
    tag = "A"
  ) +
  scale_x_discrete(labels = c("phylogeny", "immune_category_high", "pharmaceutical_class", "sex", "age_recode", "duration_convert",  "dosage_convert_ugL"))

weights_lnRR_plot
```

```{r}
#Refit the biological relevant moderators using REML
# Refit the best model using REML
mlmr.best.lnRR.reml <- rma.mv(
  yi = lnRR,
  V = lnRRVCV,
  random = list(~1 | study_id, ~1 | assay_id),
  mods = ~ immune_category_high + pharmaceutical_class                          + age_recode + dosage_convert_ugL +                              duration_convert + sex -1,
  method = "REML",
  test = "t",
  data = data,
  sparse = TRUE
)

# View the summary
summary(mlmr.best.lnRR.reml)
r2_ml(mlmr.best.lnRR.reml)

```


