---
title: "lnVR"
author: "Gabriel Melhado"
date: "2025-06-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load packages
pacman::p_load(devtools, tidyverse, metafor, patchwork, R.rsp, orchaRd, emmeans,
               ape, phytools, flextable, here, kableExtra, magrittr, metagear, rotl,
               clubSandwich, MuMIn, ggsankey)
```

```{r}
#Load Data
data <- read.csv(here("data", "data_pharma_immune.csv"))

```

```{r}
## *Calculate effect sizes and sampling variances*
# Make sure all data is numeric 
data <- data  %>%
  mutate(
    treatment_mean = as.numeric(treatment_mean),
    treatment_sd = as.numeric(treatment_sd),
    treatment_n = as.numeric(treatment_n),
    control_mean = as.numeric(control_mean),
    control_sd = as.numeric(control_sd),
    control_n = as.numeric(control_n)
  )

# Calculate log response ratio (lnRR)
lnRR <- escalc(measure = "ROM", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)


# Calculate log coefficient variation ratio (lnCVR)
lnCVR <- escalc(measure = "CVR", 
                m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
                m2i = control_mean, sd2i = control_sd, n2i = control_n, 
                data = data)

# Calculate the standardised mean difference for sensitivity analysis
SMD <- escalc(measure = "SMD", 
              m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
              m2i = control_mean, sd2i = control_sd, n2i = control_n, 
              data = data)

# Calculate log variation ratio (lnVR)
lnVR <- escalc(measure = "VR", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)

# Summary statistics of sampling variances
sampling_variance_summaries <- list(
  lnRR = summary(lnRR$vi),
  lnCVR = summary(lnCVR$vi),
  SMD = summary(SMD$vi),
  VR = summary(lnVR$vi)
)

# Calculate precision for each effect size estimate with checks
lnRR$precision <- ifelse(lnRR$vi > 0, 1 / sqrt(lnRR$vi), NA)
lnCVR$precision <- ifelse(lnCVR$vi > 0, 1 / sqrt(lnCVR$vi), NA)
SMD$precision <- ifelse(SMD$vi > 0, 1 / sqrt(SMD$vi), NA)
lnVR$precision <- ifelse(lnVR$vi > 0, 1 / sqrt(lnVR$vi), NA)


# Merge the data
effect_size_metrics_set <- data.frame(
  lnRR = lnRR$yi, lnRRv = lnRR$vi, lnRR_precision = lnRR$precision,
  lnVR = lnVR$yi, lnVRv = lnVR$vi, lnVR_precision = lnVR$precision,
  lnCVR = lnCVR$yi, lnCVRv = lnCVR$vi, lnCVR_precision = lnCVR$precision,
  SMD = SMD$yi, SMDv = SMD$vi, SMD_precision = SMD$precision,
  control_imputed = data$control_sd, treatment_imputed = data$treatment_sd
)

# Bind the effect size metrics set to the main data
data <- cbind(data, effect_size_metrics_set)

data <- subset(data, orientation != 0) #Remove immune traits with orientation "0"

# Select specific columns including the new precision columns
effect_size_metrics_set_kable <- data[, which(colnames(data) %in% c(
  "study_id","assay_id", "species_english", "pharmaceutical", "immune_trait_category",
  "lnRR", "lnRRv", "lnRR_precision", 
  "lnCVR", "lnCVRv", "lnCVR_precision", 
  "lnVR", "lnVRv", "lnVR_precision", 
  "SMD", "SMDv", "SMD_precision", 
  "control_imputed", "treatment_imputed"
))] %>% dfround(digits = 3)

# Table of the effect sizes
kable(effect_size_metrics_set_kable, "html") %>%
  kable_styling("bordered", position = "left") %>%
  scroll_box(width = "250%", height = "800px")

# Plot the distribution of effect size estimates (lnVR)
lnVR_dist_plot <- effect_size_metrics_set_kable %>%
  ggplot(aes(lnCVR)) +
  geom_histogram(fill = RColorBrewer::brewer.pal(n = 8, name = "Set2")[3], col = "black", binwidth = 0.1, alpha = 0.4) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        axis.ticks = element_line(color = "black"),
        plot.caption = element_text(size = 10, color = "gray10", face = "italic")) +
  labs(caption = "Distribution of Effect Size Estimates (lnVR)",
       x = "lnVR",
       y = "Frequency")

print(lnVR_dist_plot)

```

```{r}
## *Dependent effect size estimates*
### *Create phylogentic tree*
data <- as.data.frame(data)

data$species_latin = as.factor(data$species_latin)

taxa <- tnrs_match_names(names = levels(data$species_latin), context = "Animals")  # Match species names to the Open Tree of Life taxonomy

kable(taxa)  # Display matched species, ensuring each species has a unique match in the Open Tree of Life

taxa$unique_name <- gsub(" ", "_", taxa$unique_name)  # Replace spaces in species names with underscores

phylo_tree <- tol_induced_subtree(ott_ids = taxa$ott_id, label_format = "name")  # Generate a phylogenetic tree based on the Open Tree of Life taxonomy

ott_in_tree <- ott_id(taxa)[is_in_tree(ott_id(taxa))]  # Ensure all identifiers are present in the taxonomy

phylo_tree <- tol_induced_subtree(ott_ids = ott_in_tree)  # Generate a phylogenetic tree including all species present in the taxonomy

is.binary(phylo_tree)  # Check if tree is binary 


# Plot for the phylogenetic tree
plot(phylo_tree,
     cex= 1, #font size
     label.offset =.1,
     no.margin = TRUE)

# Compute branch length
phylo_branched <- compute.brlen(phylo_tree, method = "Grafen", power = 1)  # compute branch lengths using Grafen's method

phylo_branched$tip.label <- strip_ott_ids(phylo_branched$tip.label, remove_underscores = FALSE)  # remove ott ID from species name to match it to the data set

phylo_matrix <- vcv(phylo_branched, cor = T)  # Generate variance covariance matrix to correlate species relatedness 

data <- as.data.frame(data)
data <- data[, !duplicated(names(data))]

# Convert species_latin to lowercase
data <- mutate(data, search_string = tolower(species_latin))

data <- left_join(data, select(taxa, search_string, unique_name, ott_id), by = "search_string")  # Join data sets

data <- data[data$unique_name %in% phylo_branched$tip.label, ]  # Check that species names are well matched with the phylogenetic tree


data$phylogeny <- data$unique_name  # Rename 'unique_name' to 'phylogeny' for the models

```


```{r}
## *Variance covariance matrices*
#To account for the dependency of effect sizes estimates due to being in the same exposure group (cohort) we constructed a series of vcv matrices.

#------------------------------lnVR------------------------------#
data<- data[!is.na(data$lnVRv),]
lnVRVCV <- metafor::vcalc(vi = lnVRv, cluster = exposure_id, obs = assay_id, data = data, rho = 0.5)
lnVRVCV <- lnVRVCV + diag(1e-5, nrow(lnVRVCV))
```


```{r}
## Null model with no random effects (lnVR)
# fit a null model as default model
null_mod_lnVR <- rma.mv(yi = lnVR, 
                        V = lnVRVCV, 
                        method = "ML", 
                        test = "t", 
                        data = data, 
                        sparse = TRUE)


summary(null_mod_lnVR)

```

```{r}
## Add *assay_id* as a random effect and compare with the null model (lnVR)
mod_lnVR.assay_id <- rma.mv(yi = lnVR, 
                            V = lnVRVCV,
                            random =  ~1 | assay_id,
                            method = "ML", 
                            test = "t", 
                            data = data, 
                            sparse = T)

summary(mod_lnVR.assay_id)

anova(null_mod_lnVR, mod_lnVR.assay_id)

```

```{r}
## Add *study_id* as a random effect to the above better model (that used *assay_id* as a random effect) (lnVR)
mod_lnVR.assay_id.study_id <- rma.mv(yi = lnVR,
                                     V = lnVRVCV,
                                     random = list(~1 | study_id, 
                                                   ~1 | assay_id),
                                     method = "ML",
                                     test = "t", 
                                     data = data, 
                                     sparse = T)

summary(mod_lnVR.assay_id.study_id)

anova(mod_lnVR.assay_id, mod_lnVR.assay_id.study_id)

```

```{r}
## Add *exposure_id* as a random effect to the above better model (that used *assay_id* and *study_id* as random effets) (lnVR)
mod_lnVR.assay_id.study_id.exp_id <- rma.mv(yi = lnVR,
                                            V = lnVRVCV,
                                            random = list(~1 | study_id,
                                                          ~1 | exposure_id,
                                                          ~1 | assay_id),
                                            method = "ML",
                                            test = "t", 
                                            data = data,
                                            sparse = T)

summary(mod_lnVR.assay_id.study_id.exp_id)

anova(mod_lnVR.assay_id.study_id, mod_lnVR.assay_id.study_id.exp_id)
```

```{r}
## Add *phylogeny* as a random effect to the above better model (that used *assay_id* and *study_id* as random effets) (lnVR)
mod_lnVR.assay_id.study_id.phylogeny <- rma.mv(yi = lnVR,
                                             V = lnVRVCV,
                                             random = list(~1 | study_id, 
                                                           ~1 | assay_id,
                                                           ~1 | phylogeny),
                                             method = "ML",
                                             test = "t", 
                                             data = data,
                                             sparse = T)

summary(mod_lnVR.assay_id.study_id.phylogeny)

anova(mod_lnVR.assay_id.study_id, mod_lnVR.assay_id.study_id.phylogeny)

```


```{r}
## Add *pharmaceutical* as a random effect to the above better model (that used *assay_id* and *study_id* as random effects) (lnVR)
mod_lnVR.assay_id.study_id.pharmaceutical <- rma.mv(yi = lnVR,
                                                                 V = lnVRVCV,
                                                                 random = list(~1 | study_id,
                                                                               ~1 | assay_id,
                                                                               ~1 | pharmaceutical),
                                                                 method = "ML",
                                                                 test = "t", 
                                                                 data = data, 
                                                                 sparse = T)

summary(mod_lnVR.assay_id.study_id.pharmaceutical)
```

```{r}
### Question: Does pharmaceutical impact immune response variability?

## Intercept only model (lnVR)
# Model
lnVR_intercept_only <- rma.mv(yi = lnVR,
                              V = lnVRVCV,
                              random = list(~1 | study_id,
                                            ~1 | assay_id,
                                            ~1 | pharmaceutical,
                                            ~1 | species_latin,
                                            ~1 | phylogeny),
                              method = "REML",
                              test = "t", 
                              data = data,
                              sparse = T,
                              R = list(phylogeny = phylo_matrix))


# Summary statistics 
summary(lnVR_intercept_only)

mod_results(lnVR_intercept_only, mod = "1", data = data, group = "study_id")  
i2_ml(lnVR_intercept_only)

# Given point estimate of lnVR
lnVR_point <- lnVR_intercept_only$b[[1]]

# Calculate the percentage change
lnVR_percentage_change <- (1 - exp(lnVR_point)) * 100
lnVR_percentage_change

```

```{r}
## *Figure 2*
#Impacts of pharmaceutical exposure on fish immune response. (B) shows the difference in variances between control and treatment groups, also on a logarithmic scale, where negative values suggest a reduction in the inter-individual variability of immune response. Shorter whiskers represent 95% confidence intervals, while longer whiskers indicate 95% prediction intervals. 'k' represents the number of effect sizes, and the number of studies is in brackets. Each circle corresponds to an effect size, with its size scaled according to precision (inverse sampling error variance).

# Figure 2
intercept_only.lnVR_orchard <- orchaRd::orchard_plot(
  lnVR_intercept_only,
  group = "study_id",
  xlab = "Log Variability Ratio (lnVR)",
  g = TRUE,
  k.pos = "right",
  colour = FALSE,
  fill = TRUE,
  trunk.size = 0.8,
  legend.pos = "none",
  branch.size = 1.5,
  twig.size = 0.5
) +
  scale_fill_manual(values = metric_colours$lnVR) +
  scale_colour_manual(values = "#E6955C") +   # darker border
  scale_x_discrete(labels = c("Model estimates")) +
  theme_pub_large +
  theme(
    axis.text.y = element_text(face = "bold", size = 13, color = "black", angle = 90, vjust = 0.5, hjust = 0.5),
    panel.grid = element_blank()
  )

intercept_only.lnVR_orchard


#ggsave(here("figures", "figure2_overall_lnVR.pdf"), width = 12, height = 7, units = "cm", scale = 2, dpi = 800)
#ggsave(here("figures", "figure2_overall_lnVR.jpg"), width = 12, height = 7, units = "cm", scale = 2, dpi = 800)


```

```{r}
# Creating figure overall lnRR/lnVR
figure1_combined <- 
  intercept_only.lnRR_orchard +
  intercept_only.lnVR_orchard +
  plot_layout(ncol = 2) +
  plot_annotation(tag_levels = "A") &
  theme(
    plot.tag = element_text(
      size = 14,
      face = "bold",
      color = "black"
    )
  )


#ggsave(filename = here::here("figures", "Figure3_overall_lnRR_lnVR.pdf"), plot = figure1_combined, device = cairo_pdf, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)
#ggsave(filename = here::here("figures", "Figure3_overall_lnRR_lnVR.jpg"), plot = figure1_combined, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)


```


```{r}
#### Question: How does pharmaceutical exposure affect the variability of immune responses?

###  *Moderating effects of immune response (lnVR)*
# Model
lnVR_mod_immune_category_high <- rma.mv(yi = lnVR,
                                   V = lnVRVCV,
                                   random = list(~1 | study_id,
                                            ~1 | assay_id,
                                            ~1 | pharmaceutical,
                                            ~1 | species_latin,
                                            ~1 | phylogeny),
                                                 
                                   mods = ~immune_category_high -1,
                                   method = "REML",
                                   test = "t", 
                                   data = data,
                                   sparse = T,
                                   R = list(phylogeny = phylo_matrix))

# Summary statistics
summary(lnVR_mod_immune_category_high)

mod_results(lnVR_mod_immune_category_high, mod = "immune_category_high", data = data, group = "study_id")  

r2_ml(lnVR_mod_immune_category_high)
```


```{r}
# Figure 3
# The moderating effects of immune traits, white blood cell count (WBC), humoral-mediated response, cytokines and cell-mediated response on response variability

pal_pastel_named <- c(
  "WBC"          = "#8FBCE6",
  "Humoral-mediated" = "#F7C9A9",
  "Cytokines"    = "#D1B3E0",
  "Cell-mediated"= "#9FD5C0"
)

# 2) Build the orchard with lighter geometry
# Figure 3 (lnVR ~ immune_category_high)

immune_category_high_mod_orchard.lnVR <-
  orchaRd::orchard_plot(
    lnVR_mod_immune_category_high,   # <-- your lnVR moderator model
    group = "study_id",
    xlab  = "Log Variability Ratio (lnVR)",
    mod   = "immune_category_high",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,
    branch.size = 1.2,
    twig.size   = 0.8
  ) +
  scale_fill_manual(values = pal_pastel_named) +  # or pal_pastel if you didn't name it
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", linewidth = 0.4) +
  theme_pub_large +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.y = element_text(face = "bold", color = "black")
  ) +
  labs(title = NULL)


# 3) Shrink the big summary bubble (layer [[4]] is the summary pointrange)
immune_category_high_mod_orchard.lnVR$layers[[4]]$geom_params$fatten    <- 1.7 # default ~4

# 5) (Optional) slim the CI lines (layers [[3]] & [[4]])
immune_category_high_mod_orchard.lnVR$layers[[3]]$geom_params$linewidth <- 0.35
immune_category_high_mod_orchard.lnVR$layers[[4]]$geom_params$linewidth <- 0.35

immune_category_high_mod_orchard.lnVR

```

```{r}
# Combine Figure 3A and 3B
figure3_AB <-
  (immune_category_high_mod_orchard.lnRR |
   immune_category_high_mod_orchard.lnVR) +
  plot_annotation(tag_levels = "A") &
  theme(
    plot.tag = element_text(
      size = 18,
      face = "bold",
      color = "black"
    )
  )

#ggsave(filename = here::here("figures", "Figure4_immune_lnRR_lnVR.pdf"), plot = figure3_AB, device = cairo_pdf, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)

#ggsave(filename = here::here("figures", "Figure4_immune_lnRR_lnVR.jpg"), plot = figure3_AB, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)
```


```{r}
## Question: Do pharmaceuticals vary in their effects on fish immune response variability?

# moderate by pharmaceutical_class (lnVR)
lnVR_mod_pharmaceutical <- rma.mv(yi = lnVR,
                                        V = lnVRVCV,
                                        random = list(~1 | study_id,
                                            ~1 | assay_id,
                                            ~1 | species_latin,
                                            ~1 | phylogeny,
                                            ~1 | pharmaceutical),
                                        
                                        mods = ~pharmaceutical_class -1,
                                        method = "REML",
                                        test = "t", 
                                        data = data,
                                        sparse = T,
                                        R = list(phylogeny = phylo_matrix))

# Summary results
summary(lnVR_mod_pharmaceutical)

lnVR_pharmaceutical_mod_results <- mod_results(lnVR_mod_pharmaceutical, mod = "pharmaceutical_class", data = data, group = "study_id") 

r2_ml(lnVR_mod_pharmaceutical)
```


```{r}
### Figure 4
#The moderating effects of pharmaceutical (B) response variability in immune response. Shorter whiskers represent 95% confidence intervals, while longer whiskers indicate 95% prediction intervals. 'k' represents the number of effect sizes, and the number of studies is in brackets. Each circle corresponds to an effect size, with its size scaled according to precision (inverse sampling error variance).

pharma_colours <- c(
  "Antibiotic"       = "#D1B3E0",  # blue (WBC tone, consistent)
  "Antidepressant"   = "#F7C9A9",  # orange
  "Contraceptive"    = "#8FBCE6",  # purple
  "Anti-inflammatory" = "#9FD5C0" # teal
)


# 2) Build the orchard with lighter geometry
pharmaceutical_mod_orchard.lnVR <-
  orchaRd::orchard_plot(
    lnVR_mod_pharmaceutical,
    group = "study_id",
    xlab  = "Log Variability Ratio (lnVR)",
    mod   = "pharmaceutical_class",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,
    branch.size = 1.2,
    twig.size   = 0.8
  ) +
  scale_fill_manual(values = pharma_colours) +   # same colour mapping
  geom_vline(xintercept = 0, linetype = "dashed",
             color = "black", linewidth = 0.4) +
  theme_pub_large +
  theme(
    legend.position = "none",
    axis.text.y = element_text(face = "bold", color = "black"),
    panel.grid = element_blank()
  ) +
  labs(title = NULL)

# 3) Shrink the big summary bubble (layer [[4]] is the summary pointrange)
pharmaceutical_mod_orchard.lnVR$layers[[4]]$geom_params$fatten    <- 1.7 # default ~4

# 5) (Optional) slim the CI lines (layers [[3]] & [[4]])
pharmaceutical_mod_orchard.lnVR$layers[[3]]$geom_params$linewidth <- 0.35
pharmaceutical_mod_orchard.lnVR$layers[[4]]$geom_params$linewidth <- 0.35

pharmaceutical_mod_orchard.lnVR
```

```{r}
#Combine Figure 4A and 4B
figure4_AB <-
  (pharmaceutical_mod_orchard.lnRR | pharmaceutical_mod_orchard.lnVR) +
  plot_annotation(tag_levels = "A") &
  theme(
    plot.tag = element_text(size = 18, face = "bold", color = "black")
  )

#ggsave(filename = here::here("figures", "Figure4_immune_lnRR_lnVR.pdf"), plot = figure4_AB, device = cairo_pdf, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)

#ggsave(filename = here::here("figures", "Figure4_immune_lnRR_lnVR.jpg"), plot = figure4_AB, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)

```



```{r}
### *Moderate by concentration of pharmaceutical (lnVR)*
# Create dataframe for model with consistent dosage units
unique_dosage_units <- unique(data$dosage_unit)
print(unique_dosage_units)

data_dosage_model <- data %>% 
  filter(dosage != "not reported") %>% 
  filter(dosage_unit != "not reported") %>% 
  filter(!dosage_unit %in% c("nm", "um", "nM")) %>%
  mutate(dosage = as.numeric(dosage),
         dosage_unit = as.character(dosage_unit),
         dosage_unit_consistent = case_when(
           dosage_unit == "mg/L" ~ "ug/L", 
           dosage_unit == "ng/L" ~ "ug/L",
           dosage_unit == "ppm" ~ "ug/L", 
           TRUE ~ dosage_unit),
         dosage_convert_ugL = case_when(
           dosage_unit == "mg/L" ~ dosage * 1000,
           dosage_unit == "ng/L" ~ dosage / 1000,
           dosage_unit == "ppm" ~ dosage*1000, 
           TRUE ~ dosage)) %>% 
  filter(!is.na(dosage_convert_ugL)) %>% 
  mutate(log_dosage_convert_ugL = log(dosage_convert_ugL)) 


# Recalculate the VCV matrix based on the new data frame 
lnVRVCV_dosage <- metafor::vcalc(vi = lnVRv, cluster = exposure_id, obs = assay_id, data = data_dosage_model, rho = 0.5)
# Regularize the variance-covariance matrix by adding a small value to the diagonal
lnVRVCV_dosage_smooth <- lnVRVCV_dosage + diag(1e-5, nrow(lnVRVCV_dosage))
# Make the matrix symmetric by averaging with its transpose
lnVRVCV_dosage_smooth <- (lnVRVCV_dosage_smooth + t(lnVRVCV_dosage_smooth)) / 2

```

```{R}
## Question: Does pharmaceutical dosage influence the variability of immune response in fish?

## Model
lnVR_mod_dosage <- rma.mv(yi = lnVR,
                          V = lnVRVCV,
                          random = list(~1 | study_id,
                                            ~1 | assay_id,
                                            ~1 | pharmaceutical,
                                            ~1 | species_latin,
                                            ~1 | phylogeny),
                                        
                          mods = ~log_dosage_convert_ugL -1,
                          method = "REML",
                          test = "t", 
                          data = data_dosage_model,
                          sparse = T,
                          R = list(phylogeny = phylo_matrix))

# Summary results
summary(lnVR_mod_dosage)

dosage_mod_lnVR_results <- mod_results(lnVR_mod_dosage, mod = "log_dosage_convert_ugL", data = data_dosage_model, group = "study_id") 

r2_lnVR_dosage <- r2_ml(lnVR_mod_dosage, data_dosage_model)
r2_lnVR_dosage

```


```{r}
### *Moderate by duration of pharmaceutical (lnVR)* 
# Create dataframe for model with consistent duration units
data_duration_model <- data %>% 
  filter(!is.na(duration), duration != "not reported") %>%
  mutate(duration = as.numeric(duration),
         duration_unit = as.character(duration_unit),
         duration_unit_consistent = case_when(
           duration_unit == "minutes" ~ "hours",
           duration_unit == "days" ~ "hours",
           duration_unit == "weeks" ~ "hours",
           TRUE ~ duration_unit),
         duration_convert = case_when(
           duration_unit == "minutes" ~ duration/ 60, 
           duration_unit == "days" ~ duration*24, 
           duration_unit == "weeks" ~ duration*168,
           TRUE ~ duration))

# Recalculate the VCV matrix based on the new data frame 
lnVRVCV_duration <- metafor::vcalc(vi = lnVRv, cluster = exposure_id, obs = assay_id, data = data_duration_model, rho = 0.5)
# Regularize the variance-covariance matrix by adding a small value to the diagonal
lnVRVCV_duration_smooth <- lnVRVCV_duration + diag(1e-5, nrow(lnVRVCV_duration))
# Make the matrix symmetric by averaging with its transpose
lnVRVCV_duration_smooth <- (lnVRVCV_duration_smooth + t(lnVRVCV_duration_smooth)) / 2
```


```{R}
## Question: Does exposure duration to pharmaceutical influence the variability of immune response in fish?

# Model
lnVR_mod_duration <- rma.mv(yi = lnVR,
                            V = lnVRVCV,
                            random = list(~1 | study_id,
                                            ~1 | assay_id,
                                            ~1 | pharmaceutical,
                                            ~1 | species_latin,
                                            ~1 | phylogeny),
                                          
                            mods = ~log(duration_convert) -1,
                            method = "REML",
                            test = "t", 
                            data =data_duration_model ,
                            sparse = T,
                            R = list(phylogeny = phylo_matrix))
# Summary results
summary(lnVR_mod_duration)

lnVR_mod_duration_results <- mod_results(lnVR_mod_duration, mod = "duration_convert", data = data_duration_model, group = "study_id") 

r2_lnVR_duration <- r2_ml(lnVR_mod_duration, data_duration_model)
r2_lnVR_duration

```

```{r}
# Figure 5a)
## We illustrate the (c) moderating effects of dosage (ug/L, on a logarithmic scale) and (d) duration (hours) on the variability of immune response. The R2 values indicate the minimal variance explained by dosage and duration

# Figure 5c)
dosage_bubble_plot.lnVR <- bubble_plot(dosage_mod_lnVR_results, mod = "log_dosage_convert_ugL", group = "study_id", x = "dosage_convert_ugL",
                                       y = "lnVR", est.lwd = 1, legend.pos = "bottom.right", k.pos = "bottom.left",
                                       ci.col = "red", pi.col = "black", est.col = "black", g = TRUE) + annotate(geom = "text",
                                                                                                                 x = 7, y = 5.8, label = paste0("italic(R)^{2} == ", round(r2_lnVR_dosage[1], 4)), color = "black",
                                                                                                                 parse = TRUE, size = 4)  + 
  ggtitle("") + 
  theme(plot.title = element_text(size = 18),
        legend.position = "none", axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 14), axis.text.x = element_text(size = 14)) +
  xlab("Dosage (log10 scale)")
dosage_bubble_plot.lnVR

# Figure 5d)
duration_bubble_plot.lnVR <- bubble_plot(lnVR_mod_duration_results, mod = "duration_convert", group = "study_id", x = "duration_convert",
                                         y = "lnVR", est.lwd = 1, legend.pos = "bottom.right", k.pos = "bottom.left",
                                         ci.col = "red", pi.col = "black", est.col = "black", g = TRUE) + 
  annotate(geom = "text",x =2800, y =2.1, 
           label = paste0("italic(R)^{2} == ", round(r2_lnVR_duration[1], 4)), color = "black",
           parse = TRUE, size = 4)  + 
  ggtitle("") + 
  theme(plot.title = element_text(size = 18),
        legend.position = "none", axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 14), axis.text.x = element_text(size = 14)) +
  xlab("Duration (hours)")

duration_bubble_plot.lnVR

```

```{r}
#Combine Figure 5C and 5D
figure5_AB <-
  (dosage_bubble_plot.lnRR | dosage_bubble_plot.lnVR) +
  plot_annotation(
    tag_levels = list(c("C", "D"))
  ) &
  theme(
    plot.tag = element_text(size = 18, face = "bold", color = "black")
  )

#ggsave(filename = here::here("figures", "Figure5_dosage_lnRR_lnVR.pdf"), plot = figure5_AB, device = cairo_pdf, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)

#ggsave(filename = here::here("figures", "Figure5_dosage_lnRR_lnVR.jpg"), plot = figure5_AB, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)
```

```{r}
#Combine Figure 6E and 6F
figure6_CD <-
  (duration_bubble_plot.lnRR | duration_bubble_plot.lnVR) +
  plot_annotation(
    tag_levels = list(c("E", "F"))
  ) &
  theme(
    plot.tag = element_text(size = 18, face = "bold", color = "black")
  )

#ggsave(filename = here::here("figures", "Figure6_duration_lnRR_lnVR.pdf"), plot = figure6_CD, device = cairo_pdf, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)

#ggsave(filename = here::here("figures", "Figure6_duration_lnRR_lnVR.jpg"), plot = figure6_CD, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)
```

```{r}
#Combine Figures 4, 5 and 6

fig4_keep_tags <- wrap_elements(full = figure4_AB)
fig5_keep_tags <- wrap_elements(full = figure5_AB)
fig6_keep_tags <- wrap_elements(full = figure6_CD)

figure456_vertical <-
  fig4_keep_tags /
  fig5_keep_tags /
  fig6_keep_tags +
  plot_layout(ncol = 1)

#ggsave(filename = here::here("figures", "Figure7_duration_dose_lnRR_lnVR.pdf"), plot = figure456_vertical, device = cairo_pdf, width = 180, height = 200, units = "mm", scale = 2, dpi = 800)

#ggsave(filename = here::here("figures", "Figure7_duration_dose_lnRR_lnVR.jpg"), plot = figure456_vertical, width = 180, height = 200, units = "mm", scale = 2, dpi = 800)
```


```{r}
### Question: Is the effect of pharmaceuticals on the variability of fish immune responses sex-dependent?

#Moderate by sex (lnVR)
##Model
lnVR_mod_sex <- rma.mv(yi = lnVR,
                           V = lnVRVCV,
                           random = list(~1 | study_id,
                                            ~1 | assay_id,
                                            ~1 | pharmaceutical,
                                            ~1 | species_latin,
                                            ~1 | phylogeny),
                           mods = ~sex -1,
                           method = "REML",
                           test = "t", 
                           data = data,
                           sparse = T,
                       R = list(phylogeny = phylo_matrix))


# Summary results
summary(lnVR_mod_sex)

lnVR_sex_mod_results <- mod_results(lnVR_mod_sex, mod = "sex", data = data, group = "study_id")

r2_ml(lnVR_mod_sex)

```

```{r}
# Figure 6

lnVR_mod_sex_figure <-
  orchaRd::orchard_plot(
    lnVR_mod_sex,
    group = "study_id",
    xlab  = "Log Variability Ratio (lnVR)",
    mod   = "sex",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,
    branch.size = 1.2,
    twig.size   = 0.8
  ) +
  scale_fill_manual(values = pal_sex) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", linewidth = 0.4) +
  theme_pub_large +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.y = element_text(face = "bold", color = "black")
  ) +
  labs(title = NULL)

# Shrink summary bubble and slim summary CI line (if layer 4 is the summary layer)
lnVR_mod_sex_figure$layers[[4]]$geom_params$fatten    <- 1.7
lnVR_mod_sex_figure$layers[[4]]$geom_params$linewidth <- 0.35

lnVR_mod_sex_figure
```
```{r}
# Combine lnRR (A) and lnVR (B)
figure_sex_AB <-
  (sex_mod_orchard.lnRR | lnVR_mod_sex_figure) +
  plot_annotation(tag_levels = "A") &
  theme(
    plot.tag = element_text(size = 18, face = "bold", color = "black")
  )

figure_sex_AB

#ggsave(filename = here::here("figures", "Figure8_sex_lnRR_lnVR.pdf"), plot = figure_sex_AB, device = cairo_pdf, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)

#ggsave(filename = here::here("figures", "Figure8_sex_lnRR_lnVR.jpg"), plot = figure_sex_AB, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)

```


```{r}
#Moderate by age (lnVR)
#moderate by age (lnVR)
## 1) Recode age -> merge juvenile/embryo/larvae/eggs into "early_life_stage"
data <- data %>%
  mutate(
    age = tolower(str_trim(age)),
    age_recode = case_when(
      age %in% c("juvenile", "embryo", "larvae", "eggs") ~ "early_life_stage",
      age %in% c("adult", "not reported") ~ age,
      TRUE ~ "not reported"           # catch-all
    ),
    # choose reference level you prefer (here: "adult")
    age_recode = factor(age_recode, levels = c("adult","early_life_stage","not reported"))
  )

```

```{R}
### Question: Is the effect of pharmaceuticals on the variability of fish immune responses age-dependent?

##Model
lnVR_mod_age <- rma.mv(yi = lnVR,
                       V = lnVRVCV,
                       random = list(~1 | study_id,
                                            ~1 | assay_id,
                                            ~1 | pharmaceutical,
                                            ~1 | species_latin,
                                            ~1 | phylogeny),
                       mods = ~age_recode -1,
                       method = "REML",
                       test = "t", 
                       data = data,
                       sparse = T,
                       R = list(phylogeny = phylo_matrix))


# Summary results
summary(lnVR_mod_age)

lnVR_age_mod_results <- mod_results(lnVR_mod_age, mod = "age_recode", data = data, group = "study_id")

r2_ml(lnVR_mod_age)
```

```{r}
# Figure

age_mod_orchard.lnVR <-
  orchaRd::orchard_plot(
    lnVR_mod_age,
    group = "study_id",
    xlab  = "Log Variability Ratio (lnVR)",
    mod   = "age_recode",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,
    branch.size = 1.2,
    twig.size   = 0.8
  ) +
  scale_fill_manual(values = pal_age) +
  geom_vline(xintercept = 0, linetype = "dashed",
             color = "black", linewidth = 0.4) +
  theme_pub_large +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.y = element_text(face = "bold", color = "black")
  ) +
  labs(title = NULL)

# Shrink summary bubble and slim summary CI line (if layer 4 is summary)
age_mod_orchard.lnVR$layers[[4]]$geom_params$fatten    <- 1.7
age_mod_orchard.lnVR$layers[[4]]$geom_params$linewidth <- 0.35

age_mod_orchard.lnVR

```

```{r}
figure_age_CD <-
  (age_mod_orchard.lnRR | age_mod_orchard.lnVR) +
  plot_annotation(
    tag_levels = list(c("C", "D"))
  ) &
  theme(
    plot.tag = element_text(
      size = 18,
      face = "bold",
      color = "black"
    )
  )

#ggsave(filename = here::here("figures", "Figure9_age_lnRR_lnVR.pdf"), plot = figure_age_CD, device = cairo_pdf, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)

#ggsave(filename = here::here("figures", "Figure9_age_lnRR_lnVR.jpg"), plot = figure_age_CD, width = 180, height = 70, units = "mm", scale = 2, dpi = 800)

#Combine A,B,C,D - Figure 10
fig8_keep_tags <- wrap_elements(full = figure_sex_AB)
fig9_keep_tags <- wrap_elements(full = figure_age_CD)


figure10_vertical <-
  fig8_keep_tags /
  fig9_keep_tags +
  plot_layout(ncol = 1)

ggsave(filename = here::here("figures", "Figure10_sex_age_lnRR_lnVR.pdf"), plot = figure10_vertical, device = cairo_pdf, width = 180, height = 150, units = "mm", scale = 2, dpi = 800)

ggsave(filename = here::here("figures", "Figure10_sex_age_lnRR_lnVR.png"), plot = figure10_vertical, width = 180, height = 150, units = "mm", scale = 2, dpi = 800)

```


