---
title: "lnVR"
author: "Gabriel Melhado"
date: "2025-06-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load packages
pacman::p_load(devtools, tidyverse, metafor, patchwork, R.rsp, orchaRd, emmeans,
               ape, phytools, flextable, here, kableExtra, magrittr, metagear, rotl,
               clubSandwich, MuMIn, ggsankey)
```

```{r}
#Load Data
data <- read.csv(here("data", "data_pharma_immune.csv"))

```

```{r}
## *Calculate effect sizes and sampling variances*
# Make sure all data is numeric 
data <- data  %>%
  mutate(
    treatment_mean = as.numeric(treatment_mean),
    treatment_sd = as.numeric(treatment_sd),
    treatment_n = as.numeric(treatment_n),
    control_mean = as.numeric(control_mean),
    control_sd = as.numeric(control_sd),
    control_n = as.numeric(control_n)
  )

# Calculate log response ratio (lnRR)
lnRR <- escalc(measure = "ROM", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)


# Calculate log coefficient variation ratio (lnCVR)
lnCVR <- escalc(measure = "CVR", 
                m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
                m2i = control_mean, sd2i = control_sd, n2i = control_n, 
                data = data)

# Calculate the standardised mean difference for sensitivity analysis
SMD <- escalc(measure = "SMD", 
              m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
              m2i = control_mean, sd2i = control_sd, n2i = control_n, 
              data = data)

# Calculate log variation ratio (lnVR)
lnVR <- escalc(measure = "VR", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)

# Summary statistics of sampling variances
sampling_variance_summaries <- list(
  lnRR = summary(lnRR$vi),
  lnCVR = summary(lnCVR$vi),
  SMD = summary(SMD$vi),
  VR = summary(lnVR$vi)
)

# Calculate precision for each effect size estimate with checks
lnRR$precision <- ifelse(lnRR$vi > 0, 1 / sqrt(lnRR$vi), NA)
lnCVR$precision <- ifelse(lnCVR$vi > 0, 1 / sqrt(lnCVR$vi), NA)
SMD$precision <- ifelse(SMD$vi > 0, 1 / sqrt(SMD$vi), NA)
lnVR$precision <- ifelse(lnVR$vi > 0, 1 / sqrt(lnVR$vi), NA)


# Merge the data
effect_size_metrics_set <- data.frame(
  lnRR = lnRR$yi, lnRRv = lnRR$vi, lnRR_precision = lnRR$precision,
  lnVR = lnVR$yi, lnVRv = lnVR$vi, lnVR_precision = lnVR$precision,
  lnCVR = lnCVR$yi, lnCVRv = lnCVR$vi, lnCVR_precision = lnCVR$precision,
  SMD = SMD$yi, SMDv = SMD$vi, SMD_precision = SMD$precision,
  control_imputed = data$control_sd, treatment_imputed = data$treatment_sd
)

# Bind the effect size metrics set to the main data
data <- cbind(data, effect_size_metrics_set)

# Select specific columns including the new precision columns
effect_size_metrics_set_kable <- data[, which(colnames(data) %in% c(
  "study_id","assay_id", "species_english", "pharmaceutical", "immune_trait_category",
  "lnRR", "lnRRv", "lnRR_precision", 
  "lnCVR", "lnCVRv", "lnCVR_precision", 
  "lnVR", "lnVRv", "lnVR_precision", 
  "SMD", "SMDv", "SMD_precision", 
  "control_imputed", "treatment_imputed"
))] %>% dfround(digits = 3)

# Table of the effect sizes
kable(effect_size_metrics_set_kable, "html") %>%
  kable_styling("bordered", position = "left") %>%
  scroll_box(width = "250%", height = "800px")

# Plot the distribution of effect size estimates (lnVR)
lnVR_dist_plot <- effect_size_metrics_set_kable %>%
  ggplot(aes(lnCVR)) +
  geom_histogram(fill = RColorBrewer::brewer.pal(n = 8, name = "Set2")[3], col = "black", binwidth = 0.1, alpha = 0.4) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        axis.ticks = element_line(color = "black"),
        plot.caption = element_text(size = 10, color = "gray10", face = "italic")) +
  labs(caption = "Distribution of Effect Size Estimates (lnVR)",
       x = "lnVR",
       y = "Frequency")

print(lnVR_dist_plot)

```

```{r}
## *Dependent effect size estimates*
### *Create phylogentic tree*
data <- as.data.frame(data)

data$species_latin = as.factor(data$species_latin)

taxa <- tnrs_match_names(names = levels(data$species_latin), context = "Animals")  # Match species names to the Open Tree of Life taxonomy

kable(taxa)  # Display matched species, ensuring each species has a unique match in the Open Tree of Life

taxa$unique_name <- gsub(" ", "_", taxa$unique_name)  # Replace spaces in species names with underscores

phylo_tree <- tol_induced_subtree(ott_ids = taxa$ott_id, label_format = "name")  # Generate a phylogenetic tree based on the Open Tree of Life taxonomy

ott_in_tree <- ott_id(taxa)[is_in_tree(ott_id(taxa))]  # Ensure all identifiers are present in the taxonomy

phylo_tree <- tol_induced_subtree(ott_ids = ott_in_tree)  # Generate a phylogenetic tree including all species present in the taxonomy

is.binary(phylo_tree)  # Check if tree is binary 


# Plot for the phylogenetic tree
plot(phylo_tree,
     cex= 1, #font size
     label.offset =.1,
     no.margin = TRUE)

# Compute branch length
phylo_branched <- compute.brlen(phylo_tree, method = "Grafen", power = 1)  # compute branch lengths using Grafen's method

phylo_branched$tip.label <- strip_ott_ids(phylo_branched$tip.label, remove_underscores = FALSE)  # remove ott ID from species name to match it to the data set

phylo_matrix <- vcv(phylo_branched, cor = T)  # Generate variance covariance matrix to correlate species relatedness 

data <- as.data.frame(data)
data <- data[, !duplicated(names(data))]

# Convert species_latin to lowercase
data <- mutate(data, search_string = tolower(species_latin))

data <- left_join(data, select(taxa, search_string, unique_name, ott_id), by = "search_string")  # Join data sets

data <- data[data$unique_name %in% phylo_branched$tip.label, ]  # Check that species names are well matched with the phylogenetic tree


data$phylogeny <- data$unique_name  # Rename 'unique_name' to 'phylogeny' for the models

```


```{r}
## *Variance covariance matrices*
#To account for the dependency of effect sizes estimates due to being in the same exposure group (cohort) we constructed a series of vcv matrices.

#------------------------------lnVR------------------------------#
data<- data[!is.na(data$lnVRv),]
lnVRVCV <- metafor::vcalc(vi = lnVRv, cluster = exposure_id, obs = assay_id, data = data, rho = 0.5)
lnVRVCV <- lnVRVCV + diag(1e-5, nrow(lnVRVCV))
```


```{r}
## Null model with no random effects (lnVR)
# fit a null model as default model
null_mod_lnVR <- rma.mv(yi = lnVR, 
                        V = lnVRVCV, 
                        method = "ML", 
                        test = "t", 
                        data = data, 
                        sparse = TRUE)


summary(null_mod_lnVR)

```

```{r}
## Add *assay_id* as a random effect and compare with the null model (lnVR)
mod_lnVR.assay_id <- rma.mv(yi = lnVR, 
                            V = lnVRVCV,
                            random =  ~1 | assay_id,
                            method = "ML", 
                            test = "t", 
                            data = data, 
                            sparse = T)

summary(mod_lnVR.assay_id)

anova(null_mod_lnVR, mod_lnVR.assay_id)

```

```{r}
## Add *study_id* as a random effect to the above better model (that used *assay_id* as a random effect) (lnVR)
mod_lnVR.assay_id.study_id <- rma.mv(yi = lnVR,
                                     V = lnVRVCV,
                                     random = list(~1 | study_id, 
                                                   ~1 | assay_id),
                                     method = "ML",
                                     test = "t", 
                                     data = data, 
                                     sparse = T)

summary(mod_lnVR.assay_id.study_id)

anova(mod_lnVR.assay_id, mod_lnVR.assay_id.study_id)

```

```{r}
## Add *exposure_id* as a random effect to the above better model (that used *assay_id* and *study_id* as random effets) (lnVR)
mod_lnVR.assay_id.study_id.exp_id <- rma.mv(yi = lnVR,
                                            V = lnVRVCV,
                                            random = list(~1 | study_id,
                                                          ~1 | exposure_id,
                                                          ~1 | assay_id),
                                            method = "ML",
                                            test = "t", 
                                            data = data,
                                            sparse = T)

summary(mod_lnVR.assay_id.study_id.exp_id)

anova(mod_lnVR.assay_id.study_id, mod_lnVR.assay_id.study_id.exp_id)
```

```{r}
## Add *phylogeny* as a random effect to the above better model (that used *assay_id* and *study_id* as random effets) (lnVR)
mod_lnVR.assay_id.study_id.phylogeny <- rma.mv(yi = lnVR,
                                             V = lnVRVCV,
                                             random = list(~1 | study_id, 
                                                           ~1 | assay_id,
                                                           ~1 | phylogeny),
                                             method = "ML",
                                             test = "t", 
                                             data = data,
                                             sparse = T)

summary(mod_lnVR.assay_id.study_id.phylogeny)

anova(mod_lnVR.assay_id.study_id, mod_lnVR.assay_id.study_id.phylogeny)

```


```{r}
## Add *pharmaceutical_class* as a random effect to the above better model (that used *assay_id* and *study_id* as random effects) (lnVR)
mod_lnVR.assay_id.study_id.pharmaceutical_class <- rma.mv(yi = lnVR,
                                                                 V = lnVRVCV,
                                                                 random = list(~1 | study_id,
                                                                               ~1 | assay_id,
                                                                               ~1 | pharmaceutical_class),
                                                                 method = "ML",
                                                                 test = "t", 
                                                                 data = data, 
                                                                 sparse = T)

summary(mod_lnVR.assay_id.study_id.pharmaceutical_class)
```

```{r}
## *Intercept only model (lnVR)*
# Model
lnVR_intercept_only <- rma.mv(yi = lnVR,
                              V = lnVRVCV,
                              random = list(~1 | study_id,
                                            ~1 | assay_id),
                              method = "REML",
                              test = "t", 
                              data = data,
                              sparse = T)


# Summary statistics 
summary(lnVR_intercept_only)

mod_results(lnVR_intercept_only, mod = "1", data = data, group = "study_id")  
i2_ml(lnVR_intercept_only)

# Given point estimate of lnVR
lnVR_point <- lnVR_intercept_only$b[[1]]

# Calculate the percentage change
lnVR_percentage_change <- (1 - exp(lnVR_point)) * 100
lnVR_percentage_change

```

```{r}
## *Figure 2*
#Impacts of pharmaceutical exposure on fish immune response. (B) shows the difference in variances between control and treatment groups, also on a logarithmic scale, where negative values suggest a reduction in the inter-individual variability of immune response. Shorter whiskers represent 95% confidence intervals, while longer whiskers indicate 95% prediction intervals. 'k' represents the number of effect sizes, and the number of studies is in brackets. Each circle corresponds to an effect size, with its size scaled according to precision (inverse sampling error variance).

# Figure 2
intercept_only.lnVR__orchard <- orchaRd::orchard_plot(lnVR_intercept_only,
                                                      group = "study_id",
                                                      xlab = "lnVR",
                                                      g = TRUE,
                                                      k.pos = "right",
                                                      colour = FALSE,
                                                      fill = TRUE,  
                                                      trunk.size = 0.8, 
                                                      legend.pos = "none",
                                                      branch.size = 1.5,
                                                      twig.size = 0.5) +
  scale_fill_manual(values = RColorBrewer::brewer.pal(8, "Dark2")[2]) +
  scale_x_discrete(labels = c("Model estimates")) +
  theme(
    panel.grid = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

# Display the plot
intercept_only.lnVR__orchard


```

```{r}
###  *Moderating effects of immune response (lnVR)*
# Model
lnVR_mod_immune_category_high <- rma.mv(yi = lnVR,
                                   V = lnVRVCV,
                                   random = list(~1 | study_id,
                                                 ~1 | assay_id),
                                                 
                                   mods = ~immune_category_high -1,
                                   method = "REML",
                                   test = "t", 
                                   data = data,
                                   sparse = T)

# Summary statistics
summary(lnVR_mod_immune_category_high)

mod_results(lnVR_mod_immune_category_high, mod = "immune_category_high", data = data, group = "study_id")  

r2_ml(lnVR_mod_immune_category_high)
```

```{r}
# Figure 4B
immune_category_high_mod_orchard.lnVR <- orchaRd::orchard_plot(lnVR_mod_immune_category_high,
                                                             group = "study_id", 
                                                             xlab = "lnVR",
                                                             
                                                             mod = "immune_category_high",
                                                             g = TRUE,
                                                             k.pos = "right",
                                                             colour = FALSE,
                                                             fill = TRUE,  
                                                             legend.pos = "none",
                                                             trunk.size = 3., 
                                                             branch.size = 1.5,
                                                             twig.size = 1) +
  scale_fill_viridis_d(option = "plasma") +  # Ensures enough colors
  theme(axis.text.y = element_text(angle = 0)) +  # Make y-axis labels straight
  plot_annotation(tag_levels = "A")

immune_category_high_mod_orchard.lnVR
```


```{r}
# 1) Soft pastel palette (4 classes shown in your plot)
pal_pastel <- c("#BFD3E6", "#F7C9A9", "#D1B3E0", "#B9E3C6")

# 2) Build the orchard with lighter geometry
immune_category_high_mod_orchard.lnVR <-
  orchaRd::orchard_plot(
    lnVR_mod_immune_category_high,
    group = "study_id",
    xlab  = "lnVR",
    mod   = "immune_category_high",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,   # thinner summary CI line
    branch.size = 1.2,   # thinner study CI lines
    twig.size   = 0.8    # smaller study dots
  ) +
  # Pastel colours
  scale_fill_manual(values = pal_pastel) +
  # Axis-only look + zero line
  theme_classic(base_size = 11) +
  theme(
    axis.text.y = element_text(angle = 0),
    legend.position = "none"
  ) +
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.4, alpha = 0.7)

# 3) Shrink the big summary bubble (layer [[4]] is the summary pointrange)
immune_category_high_mod_orchard.lnVR$layers[[4]]$geom_params$fatten    <- 1.7 # default ~4

# 5) (Optional) slim the CI lines (layers [[3]] & [[4]])
immune_category_high_mod_orchard.lnVR$layers[[3]]$geom_params$linewidth <- 0.35
immune_category_high_mod_orchard.lnVR$layers[[4]]$geom_params$linewidth <- 0.35

immune_category_high_mod_orchard.lnVR

```


```{r}
# Figure 3b)
# Step 1: Create a new data frame with one row per immune_category_high
trait_levels <- data.frame(immune_category_high = sort(unique(data$immune_category_high)))

# Step 2: Create the model matrix
X <- model.matrix(~ immune_category_high - 1, data = trait_levels)

# Step 3: Get predictions from the model
preds <- predict(lnVR_mod_immune_category_high, newmods = X, level = 95)

# Step 4: Build the plot data frame
immune_plot_data <- data.frame(
  immune_category_high = trait_levels$immune_category_high,
  estimate = preds$pred,
  ci.lb = preds$ci.lb,
  ci.ub = preds$ci.ub
)

# Step 5: Order the traits by effect size if desired
immune_plot_data <- immune_plot_data %>%
  arrange(estimate) %>%
  mutate(immune_category_high = factor(immune_category_high, levels = immune_category_high))

# Step 6: Plot using ggplot2 with no color variation
ggplot(immune_plot_data, aes(x = estimate, y = immune_category_high)) +
  geom_point(color = "black", size = 2) +
  geom_errorbarh(aes(xmin = ci.lb, xmax = ci.ub), color = "black", height = 0.2) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "lnVR", y = NULL) +
  theme_minimal() +
  theme(axis.text.y = element_text(angle = 0, size = 10))
```


```{r}
#moderate by pharmaceutical (lnRV)
lnVR_mod_pharmaceutical_class <- rma.mv(yi = lnVR,
                                        V = lnVRVCV,
                                        random = list(~1 | study_id,
                                                      ~1 | assay_id),
                                        
                                        mods = ~pharmaceutical_class -1,
                                        method = "REML",
                                        test = "t", 
                                        data = data,
                                        sparse = T)

# Summary results
summary(lnVR_mod_pharmaceutical_class)

lnVR_pharmaceutical_class_mod_results <- mod_results(lnVR_mod_pharmaceutical_class, mod = "pharmaceutical_class", data = data, group = "study_id") 

r2_ml(lnVR_mod_pharmaceutical_class)
```

```{r}
### *Figure 4*
#The moderating effects of pharmaceutical (B) response variability in immune response. Shorter whiskers represent 95% confidence intervals, while longer whiskers indicate 95% prediction intervals. 'k' represents the number of effect sizes, and the number of studies is in brackets. Each circle corresponds to an effect size, with its size scaled according to precision (inverse sampling error variance).

# Figure 4B
pharmaceutical_class_mod_orchard.lnVR <- orchaRd::orchard_plot(lnVR_mod_pharmaceutical_class,
                                                             group = "study_id", 
                                                             xlab = "lnVR",
                                                             
                                                             mod = "pharmaceutical_class",
                                                             g = TRUE,
                                                             k.pos = "right",
                                                             colour = FALSE,
                                                             fill = TRUE,  
                                                             legend.pos = "none",
                                                             trunk.size = 3., 
                                                             branch.size = 1.5,
                                                             twig.size = 1) +
  scale_fill_viridis_d(option = "plasma") +  # Ensures enough colors
  theme(axis.text.y = element_text(angle = 0)) +  # Make y-axis labels straight
  plot_annotation(tag_levels = "A")

pharmaceutical_class_mod_orchard.lnVR

```

```{r}
# 1) Soft pastel palette (4 classes shown in your plot)
pal_pastel <- c("#BFD3E6", "#F7C9A9", "#D1B3E0", "#B9E3C6")

# 2) Build the orchard with lighter geometry
pharmaceutical_class_mod_orchard.lnVR <-
  orchaRd::orchard_plot(
    lnVR_mod_pharmaceutical_class,
    group = "study_id",
    xlab  = "lnVR",
    mod   = "pharmaceutical_class",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,   # thinner summary CI line
    branch.size = 1.2,   # thinner study CI lines
    twig.size   = 0.8    # smaller study dots
  ) +
  # Pastel colours
  scale_fill_manual(values = pal_pastel) +
  # Axis-only look + zero line
  theme_classic(base_size = 11) +
  theme(
    axis.text.y = element_text(angle = 0),
    legend.position = "none"
  ) +
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.4, alpha = 0.7)

# 3) Shrink the big summary bubble (layer [[4]] is the summary pointrange)
pharmaceutical_class_mod_orchard.lnVR$layers[[4]]$geom_params$fatten    <- 1.7 # default ~4

# 5) (Optional) slim the CI lines (layers [[3]] & [[4]])
pharmaceutical_class_mod_orchard.lnVR$layers[[3]]$geom_params$linewidth <- 0.35
pharmaceutical_class_mod_orchard.lnVR$layers[[4]]$geom_params$linewidth <- 0.35

pharmaceutical_class_mod_orchard.lnVR
```



```{r}
# Step 1: Create a data frame with one row per pharmaceutical_class
pharma_levels_lnVR <- data.frame(pharmaceutical_class = sort(unique(data$pharmaceutical_class)))

# Step 2: Create the model matrix
X_pharma_lnVR <- model.matrix(~ pharmaceutical_class - 1, data = pharma_levels_lnVR)

# Step 3: Get predictions from the model
pharma_preds_lnVR <- predict(lnVR_mod_pharmaceutical_class, newmods = X_pharma_lnVR, level = 95)

# Step 4: Build the plot data frame
pharma_plot_data_lnVR <- data.frame(
  pharmaceutical_class = pharma_levels_lnVR$pharmaceutical_class,
  estimate = pharma_preds_lnVR$pred,
  ci.lb = pharma_preds_lnVR$ci.lb,
  ci.ub = pharma_preds_lnVR$ci.ub
)

# Step 5: Order the classes by effect size
pharma_plot_data_lnVR <- pharma_plot_data_lnVR %>%
  arrange(estimate) %>%
  mutate(pharmaceutical_class = factor(pharmaceutical_class, levels = pharmaceutical_class))

# Step 6: Plot
ggplot(pharma_plot_data_lnVR, aes(x = estimate, y = pharmaceutical_class)) +
  geom_point(color = "black", size = 2) +
  geom_errorbarh(aes(xmin = ci.lb, xmax = ci.ub), color = "black", height = 0.2) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "lnVR", y = NULL) +
  theme_minimal() +
  theme(axis.text.y = element_text(angle = 0, size = 10))

```

```{r}
### *Moderate by concentration of pharmaceutical (lnVR)*
# Create dataframe for model with consistent dosage units
unique_dosage_units <- unique(data$dosage_unit)
print(unique_dosage_units)

data_dosage_model <- data %>% 
  filter(dosage != "not reported") %>% 
  filter(dosage_unit != "not reported") %>% 
  filter(!dosage_unit %in% c("nm", "um", "nM")) %>%
  filter(dosage_adm == "waterborne") %>%  # Filter for waterborne exposure
  mutate(dosage = as.numeric(dosage),
         dosage_unit = as.character(dosage_unit),
         dosage_unit_consistent = case_when(
           dosage_unit == "mg/L" ~ "ug/L", 
           dosage_unit == "ng/L" ~ "ug/L",
           dosage_unit == "ppm" ~ "ug/L", 
           TRUE ~ dosage_unit),
         dosage_convert_ugL = case_when(
           dosage_unit == "mg/L" ~ dosage * 1000,
           dosage_unit == "ng/L" ~ dosage / 1000,
           dosage_unit == "ppm" ~ dosage*1000, 
           TRUE ~ dosage)) %>% 
  filter(!is.na(dosage_convert_ugL)) %>% 
  mutate(log_dosage_convert_ugL = log(dosage_convert_ugL)) 


# Recalculate the VCV matrix based on the new data frame 
lnVRVCV_dosage <- metafor::vcalc(vi = lnVRv, cluster = exposure_id, obs = assay_id, data = data_dosage_model, rho = 0.5)
# Regularize the variance-covariance matrix by adding a small value to the diagonal
lnVRVCV_dosage_smooth <- lnVRVCV_dosage + diag(1e-5, nrow(lnVRVCV_dosage))
# Make the matrix symmetric by averaging with its transpose
lnVRVCV_dosage_smooth <- (lnVRVCV_dosage_smooth + t(lnVRVCV_dosage_smooth)) / 2

## Model
lnVR_mod_dosage <- rma.mv(yi = lnVR,
                          V = lnVRVCV,
                          random = list(~1 | study_id,
                                        ~1 | assay_id),
                                        
                          mods = ~log_dosage_convert_ugL -1,
                          method = "REML",
                          test = "t", 
                          data = data_dosage_model,
                          sparse = T)

# Summary results
summary(lnVR_mod_dosage)

dosage_mod_lnVR_results <- mod_results(lnVR_mod_dosage, mod = "log_dosage_convert_ugL", data = data_dosage_model, group = "study_id") 

r2_lnVR_dosage <- r2_ml(lnVR_mod_dosage, data_dosage_model)
r2_lnVR_dosage
```

```{r}
### *Moderate by duration of pharmaceutical (lnVR)* 
# Create dataframe for model with consistent duration units
data_duration_model <- data %>% 
  filter(!is.na(duration), duration != "not reported") %>%
  mutate(duration = as.numeric(duration),
         duration_unit = as.character(duration_unit),
         duration_unit_consistent = case_when(
           duration_unit == "minutes" ~ "hours",
           duration_unit == "days" ~ "hours",
           duration_unit == "weeks" ~ "hours",
           TRUE ~ duration_unit),
         duration_convert = case_when(
           duration_unit == "minutes" ~ duration/ 60, 
           duration_unit == "days" ~ duration*24, 
           duration_unit == "weeks" ~ duration*168,
           TRUE ~ duration))

# Recalculate the VCV matrix based on the new data frame 
lnVRVCV_duration <- metafor::vcalc(vi = lnVRv, cluster = exposure_id, obs = assay_id, data = data_duration_model, rho = 0.5)
# Regularize the variance-covariance matrix by adding a small value to the diagonal
lnVRVCV_duration_smooth <- lnVRVCV_duration + diag(1e-5, nrow(lnVRVCV_duration))
# Make the matrix symmetric by averaging with its transpose
lnVRVCV_duration_smooth <- (lnVRVCV_duration_smooth + t(lnVRVCV_duration_smooth)) / 2

## Model
lnVR_mod_duration <- rma.mv(yi = lnVR,
                            V = lnVRVCV,
                            random = list(~1 | study_id,
                                          ~1 | assay_id),
                                          
                            mods = ~log(duration_convert) -1,
                            method = "REML",
                            test = "t", 
                            data =data_duration_model ,
                            sparse = T)
# Summary results
summary(lnVR_mod_duration)

lnVR_mod_duration_results <- mod_results(lnVR_mod_duration, mod = "duration_convert", data = data_duration_model, group = "study_id") 

r2_lnVR_duration <- r2_ml(lnVR_mod_duration, data_duration_model)
r2_lnVR_duration

```

```{r}
# Figure 5c)
dosage_bubble_plot.lnVR <- bubble_plot(dosage_mod_lnVR_results, mod = "log_dosage_convert_ugL", group = "study_id", x = "dosage_convert_ugL",
                                       y = "lnVR", est.lwd = 1, legend.pos = "bottom.right", k.pos = "bottom.left",
                                       ci.col = "red", pi.col = "black", est.col = "black", g = TRUE) + annotate(geom = "text",
                                                                                                                 x = 7, y = 5.8, label = paste0("italic(R)^{2} == ", round(r2_lnVR_dosage[1], 4)), color = "black",
                                                                                                                 parse = TRUE, size = 4)  + 
  ggtitle("") + 
  theme(plot.title = element_text(size = 18),
        legend.position = "none", axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 14), axis.text.x = element_text(size = 14)) +
  xlab("Dosage")
dosage_bubble_plot.lnVR

# Figure 5d)
duration_bubble_plot.lnVR <- bubble_plot(lnVR_mod_duration_results, mod = "duration_convert", group = "study_id", x = "duration_convert",
                                         y = "lnVR", est.lwd = 1, legend.pos = "bottom.right", k.pos = "bottom.left",
                                         ci.col = "red", pi.col = "black", est.col = "black", g = TRUE) + 
  annotate(geom = "text",x =2800, y =2.1, 
           label = paste0("italic(R)^{2} == ", round(r2_lnVR_duration[1], 4)), color = "black",
           parse = TRUE, size = 4)  + 
  ggtitle("") + 
  theme(plot.title = element_text(size = 18),
        legend.position = "none", axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 14), axis.text.x = element_text(size = 14)) +
  xlab("Duration")

duration_bubble_plot.lnVR

```

```{r}
# Figure 6) Dose–response on lnVR
dosage_bubble_plot.lnVR <- bubble_plot(
  dosage_mod_lnVR_results,
  mod = "log_dosage_convert_ugL",
  group = "study_id",
  x = "dosage_convert_ugL",
  y = "lnVR",
  est.lwd = 1,
  legend.pos = "bottom.right",
  k.pos = "bottom.left",
  ci.col = "red",
  pi.col = "black",
  est.col = "black",
  g = TRUE
) +
  # Add R2 annotation
  annotate(
    geom = "text",
    x = 7, y = 5.8,
    label = paste0("italic(R)^{2} == ", round(r2_lnVR_dosage[1], 4)),
    color = "black",
    parse = TRUE, size = 4
  ) +
  # Axis labels with units and log scale notation
  xlab(expression(paste("Dosage (", mu, "g/L - log"[10], " scale)"))) +
  ylab("lnVR") +
  ggtitle("") +
  # Clean theme: remove grid, keep axes
  theme_classic(base_size = 14) +
  theme(
    plot.title   = element_text(size = 18),
    legend.position = "none",
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    axis.text.x  = element_text(size = 14),
    axis.text.y  = element_text(size = 14)
  )

dosage_bubble_plot.lnVR

```


```{r}
#Moderate by phylogeny (lnRV)
# Model
lnVR_mod_fish_phylogeny <- rma.mv(yi = lnVR,
                               V = lnVRVCV,
                               random = list(~1 | study_id,
                                             ~1 | assay_id
                               ),
                               mods = ~phylogeny -1,
                               method = "REML",
                               test = "t", 
                               data = data,
                               sparse = T)

# Summary results
summary(lnVR_mod_fish_phylogeny)

r2_ml(lnVR_mod_fish_phylogeny)


lnVR_phylogeny_mod_results <- mod_results(lnVR_mod_fish_phylogeny, mod = "phylogeny", data = data, group = "study_id")  


```

```{r}
# Figure 6B)
fish_phylogeny_mod_orchard.lnVR <- orchaRd::orchard_plot(lnVR_mod_fish_phylogeny,
                                                      group = "study_id", 
                                                      xlab = "lnVR",
                                                      
                                                      mod = "phylogeny",
                                                      g = TRUE,
                                                      k.pos = "right",
                                                      colour = FALSE,
                                                      fill = TRUE,  
                                                      legend.pos = "none",
                                                      trunk.size = 3., 
                                                      branch.size = 1.5,
                                                      twig.size = 1) +
  scale_fill_viridis_d(option = "plasma") +  # Ensures enough colors
  theme(axis.text.y = element_text(angle = 0)) +  # Make y-axis labels straight
  plot_annotation(tag_levels = "A")


print(fish_phylogeny_mod_orchard.lnVR)
```

```{r}
# Step 1: Create a data frame with one row per fish_phylogeny
fish_phylogeny_levels_lnVR <- data.frame(phylogeny = sort(unique(data$phylogeny)))

# Step 2: Create the model matrix
X_fish_phylogeny_lnVR <- model.matrix(~ phylogeny - 1, data = fish_phylogeny_levels_lnVR)

# Step 3: Get predictions from the model
fish_phylogeny_preds_lnVR <- predict(lnVR_mod_fish_phylogeny, newmods = X_fish_phylogeny_lnVR, level = 95)

# Step 4: Build the plot data frame
fish_phylogeny_plot_data_lnVR <- data.frame(
  phylogeny = fish_phylogeny_levels_lnVR$phylogeny,
  estimate = fish_phylogeny_preds_lnVR$pred,
  ci.lb = fish_phylogeny_preds_lnVR$ci.lb,
  ci.ub = fish_phylogeny_preds_lnVR$ci.ub
)

# Step 5: Order phylogeny by effect size
fish_phylogeny_plot_data_lnVR <- fish_phylogeny_plot_data_lnVR %>%
  arrange(estimate) %>%
  mutate(phylogeny = factor(phylogeny, levels = phylogeny))

# Step 6: Plot
ggplot(fish_phylogeny_plot_data_lnVR, aes(x = estimate, y = phylogeny)) +
  geom_point(color = "black", size = 2) +
  geom_errorbarh(aes(xmin = ci.lb, xmax = ci.ub), color = "black", height = 0.2) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "lnVR", y = NULL) +
  theme_minimal() +
  theme(axis.text.y = element_text(angle = 0, size = 10))
```

```{r}
#Moderate by sex (lnVR)
##Model
lnVR_mod_sex <- rma.mv(yi = lnVR,
                           V = lnVRVCV,
                           random = list(~1 | study_id,
                                         ~1 | assay_id),
                           mods = ~sex -1,
                           method = "REML",
                           test = "t", 
                           data = data,
                           sparse = T)


# Summary results
summary(lnVR_mod_sex)

lnVR_sex_mod_results <- mod_results(lnVR_mod_sex, mod = "sex", data = data, group = "study_id")

r2_ml(lnVR_mod_sex)

```

```{r}
lnVR_mod_sex_figure <-
  orchaRd::orchard_plot(
    lnVR_mod_sex,
    group = "study_id",
    xlab  = "lnVR",
    mod   = "sex",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,   # thinner summary CI line
    branch.size = 1.2,   # thinner study CI lines
    twig.size   = 0.8    # smaller study dots
  ) +
  scale_fill_manual(values = pal_pastel) +    # pastel palette
  # Clean, axis-only look
  theme_classic(base_size = 11) +
  theme(
    axis.text.y = element_text(angle = 0),
    legend.position = "none"
  ) +
  # Reference at no effect
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(title = NULL) +
  patchwork::plot_annotation(tag_levels = "A")  # if you’re using patchwork

# shrink the summary bubble and the PI line on the summary layer
lnVR_mod_sex_figure$layers[[4]]$geom_params$fatten    <- 1.7  # default is 4
lnVR_mod_sex_figure$layers[[4]]$geom_params$linewidth <- 0.35 # ggplot ≥3.4

lnVR_mod_sex_figure
```


```{r}
#Moderate by age (lnVR)
#moderate by age (lnVR)
## 1) Recode age -> merge juvenile/embryo/larvae/eggs into "early_life_stage"
data <- data %>%
  mutate(
    age = tolower(str_trim(age)),
    age_recode = case_when(
      age %in% c("juvenile", "embryo", "larvae", "eggs") ~ "early_life_stage",
      age %in% c("adult", "not reported") ~ age,
      TRUE ~ "not reported"           # catch-all
    ),
    # choose reference level you prefer (here: "adult")
    age_recode = factor(age_recode, levels = c("adult","early_life_stage","not reported"))
  )

##Model
lnVR_mod_age <- rma.mv(yi = lnVR,
                       V = lnVRVCV,
                       random = list(~1 | study_id,
                                     ~1 | assay_id),
                       mods = ~age_recode -1,
                       method = "REML",
                       test = "t", 
                       data = data,
                       sparse = T)


# Summary results
summary(lnVR_mod_age)

lnVR_age_mod_results <- mod_results(lnVR_mod_age, mod = "age_recode", data = data, group = "study_id")

r2_ml(lnVR_mod_age)
```

```{r}
age_mod_orchard.lnVR <-
  orchaRd::orchard_plot(
    lnVR_mod_age,
    group = "study_id",
    xlab  = "lnVR",
    mod   = "age_recode",
    g     = TRUE,
    k.pos = "right",
    colour = FALSE,
    fill   = TRUE,
    trunk.size  = 2.4,   # thinner summary CI line
    branch.size = 1.2,   # thinner study CI lines
    twig.size   = 0.8    # smaller study dots
  ) +
  scale_fill_manual(values = pal_pastel) +    # pastel palette
  # Clean, axis-only look
  theme_classic(base_size = 11) +
  theme(
    axis.text.y = element_text(angle = 0),
    legend.position = "none"
  ) +
  # Reference at no effect
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(title = NULL) +
  patchwork::plot_annotation(tag_levels = "A")  # if you’re using patchwork

# shrink the summary bubble and the PI line on the summary layer
age_mod_orchard.lnVR$layers[[4]]$geom_params$fatten    <- 1.7  # default is 4
age_mod_orchard.lnVR$layers[[4]]$geom_params$linewidth <- 0.35 # ggplot ≥3.4

age_mod_orchard.lnVR
```



```{r}
# **Model selection and multi-model inference**
## *lnVR model selection and multi-model inference*

# Create a data frame with only the required columns
dosage_duration_set <- data.frame(
  dosage_convert_ugL = data_dosage_model$dosage_convert_ugL,
  duration_convert = data_duration_model$duration_convert
)

# Bind these columns to `data`
data <- cbind(data, dosage_duration_set)

#Model lnVR
mlmr.full.lnVR <- rma.mv(yi = lnVR, 
                         V = lnVRVCV, 
                         random = list(~1 | study_id,
                                       ~1 | assay_id),
                         mods = ~ immune_category_high + pharmaceutical_class + phylogeny + age                                 + dosage_convert_ugL + duration_convert + sex,
                         method = "REML", 
                         test = "t", 
                         data = data, 
                         sparse = TRUE)

r2_ml(mlmr.full.lnVR, data = data)

eval(metafor:::.MuMIn)  # use eval() to extract helper functions from MuMIn and make them usable in metafor.

mlmr.dredge.lnVR <- dredge(mlmr.full.lnVR, beta = "none", evaluate = TRUE, rank = "AICc", trace = 2)

# Multimodel inference
summary(mlmr.full.lnVR)

# Select "best" models based on delta <= 2
best_model_vr <- subset(mlmr.dredge.lnVR, delta <= 2, recalc.weights = FALSE)

# Display the results in a scrollable kable table
best_model_vr %>%
  kable("html") %>%
  kable_styling("bordered", position = "left") %>%
  scroll_box(width = "100%", height = "800px")

# Relative importance values for the predictors
weights_lnVR <- sw(mlmr.dredge.lnVR)

# Convert the named vector into a data frame
weights_lnVR_df <- data.frame(
  predictor = names(weights_lnVR),  
  weight = as.numeric(weights_lnVR),
  R2_marginal = c(0.08257499, 0.1268721, 0.008088331, 0.01655531, 0.007386313, 0.0008732072, 0.02898393))

summary(weights_lnVR_df)

```

```{r}
# lnVR model selection plot
weights_lnVR_plot <- weights_lnVR_df %>% 
  ggplot(aes(x = reorder(predictor, weight), y = weight)) +
  geom_col(width = 0.8, alpha = 0.7) +
  coord_flip() + 
  scale_y_continuous(
    limits = c(0, 1.2),  
    breaks = seq(0, 1, by = 0.2),
    expand = c(0, 0)
  ) +
  geom_text(aes(label = scales::percent(weight, accuracy = 1)), 
            size = 6, position = position_stack(vjust = 0.5), 
            color = "white", fontface = "bold") +
  geom_text(aes(y = 1.1, label = paste0("R2 = ", round(R2_marginal, 2))), 
            size = 4, 
            fontface = "italic", 
            color = "red") +
  theme_bw() +
  guides(size = "none") +
  theme(
    legend.position = "none",
    axis.text = element_text(color = "black"),
    axis.title = element_text(face = "bold", color = "black"),
    plot.caption = element_text(size = 10, color = "gray10", face = "italic")
  ) +
  labs(
    caption = "The value in each bar is the relative importance of each moderator based on Akaike weights",
    y = "Akaike Weights",
    x = "Moderators",
    tag = "B"
  ) +
  scale_x_discrete(labels = c("dosage_convert_ugL", "duration_convert", "sex",  "pharmaceutical_class", "age", "immune_trait_category", "phylogeny"))

weights_lnVR_plot

```

```{r}
#Refit the biological relevant moderators using REML
# Refit the best model using REML
mlmr.best.lnVR.reml <- rma.mv(
  yi = lnVR,
  V = lnVRVCV,
  random = list(~1 | study_id, ~1 | assay_id),
  mods = ~ dosage_convert_ugL + immune_category_high + pharmaceutical_class,
  method = "REML",
  test = "t",
  data = data,
  sparse = TRUE
)

# View the summary
summary(mlmr.best.lnVR.reml)
r2_ml(mlmr.best.lnVR.reml)

```

