---
title: "SMD"
author: "Gabriel Melhado"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load packages
pacman::p_load(devtools, tidyverse, metafor, patchwork, R.rsp, orchaRd, emmeans,
               ape, phytools, flextable, here, kableExtra, magrittr, metagear, rotl,
               clubSandwich, MuMIn, ggsankey)
```

```{r}
#Load Data
data <- read.csv(here("data", "data_pharma_immune.csv"))

```


```{r}
## Calculate effect sizes and sampling variances
# Make sure all data is numeric 
data <- data  %>%
  mutate(
    treatment_mean = as.numeric(treatment_mean),
    treatment_sd = as.numeric(treatment_sd),
    treatment_n = as.numeric(treatment_n),
    control_mean = as.numeric(control_mean),
    control_sd = as.numeric(control_sd),
    control_n = as.numeric(control_n)
  )

# Calculate log response ratio (lnRR)
lnRR <- escalc(measure = "ROM", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)


# Calculate log coefficient variation ratio (lnCVR)
lnCVR <- escalc(measure = "CVR", 
                m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
                m2i = control_mean, sd2i = control_sd, n2i = control_n, 
                data = data)

# Calculate the standardised mean difference for sensitivity analysis
SMD <- escalc(measure = "SMD", 
              m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
              m2i = control_mean, sd2i = control_sd, n2i = control_n, 
              data = data)

# Calculate log variation ratio (lnVR)
lnVR <- escalc(measure = "VR", 
               m1i = treatment_mean, sd1i = treatment_sd, n1i = treatment_n, 
               m2i = control_mean, sd2i = control_sd, n2i = control_n, 
               data = data)

# Summary statistics of sampling variances
sampling_variance_summaries <- list(
  lnRR = summary(lnRR$vi),
  lnCVR = summary(lnCVR$vi),
  SMD = summary(SMD$vi),
  VR = summary(lnVR$vi)
)

# Calculate precision for each effect size estimate with checks
lnRR$precision <- ifelse(lnRR$vi > 0, 1 / sqrt(lnRR$vi), NA)
lnCVR$precision <- ifelse(lnCVR$vi > 0, 1 / sqrt(lnCVR$vi), NA)
SMD$precision <- ifelse(SMD$vi > 0, 1 / sqrt(SMD$vi), NA)
lnVR$precision <- ifelse(lnVR$vi > 0, 1 / sqrt(lnVR$vi), NA)


# Merge the data
effect_size_metrics_set <- data.frame(
  lnRR = lnRR$yi, lnRRv = lnRR$vi, lnRR_precision = lnRR$precision,
  lnVR = lnVR$yi, lnVRv = lnVR$vi, lnVR_precision = lnVR$precision,
  lnCVR = lnCVR$yi, lnCVRv = lnCVR$vi, lnCVR_precision = lnCVR$precision,
  SMD = SMD$yi, SMDv = SMD$vi, SMD_precision = SMD$precision,
  control_imputed = data$control_sd, treatment_imputed = data$treatment_sd
)

# Bind the effect size metrics set to the main data
data <- cbind(data, effect_size_metrics_set)

#Flip the sign (change effect sizes direction)
data <- subset(data, orientation != 0) #Remove immune traits with orientation "0"
data$lnRR <- ifelse(data$orientation == "-1", -1 * data$lnRR, data$lnRR)


# Select specific columns including the new precision columns
effect_size_metrics_set_kable <- data[, which(colnames(data) %in% c(
  "study_id","assay_id", "species_english", "pharmaceutical", "immune_trait_category",
  "lnRR", "lnRRv", "lnRR_precision", 
  "lnCVR", "lnCVRv", "lnCVR_precision", 
  "lnVR", "lnVRv", "lnVR_precision", 
  "SMD", "SMDv", "SMD_precision", 
  "control_imputed", "treatment_imputed"
))] %>% dfround(digits = 3)

# Table of the effect sizes
kable(effect_size_metrics_set_kable, "html") %>%
  kable_styling("bordered", position = "left") %>%
  scroll_box(width = "250%", height = "800px")

# Figure 1
# Plot the distribution of effect size estimates (lnRR)
lnRR_dist_plot <- effect_size_metrics_set_kable %>%
  ggplot(aes(lnRR)) +
  geom_histogram(fill = RColorBrewer::brewer.pal(n = 8, name = "Set2")[2], col = "black", binwidth = 0.1, alpha = 0.4) +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        axis.ticks = element_line(color = "black"),
        plot.caption = element_text(size = 10, color = "gray10", face = "italic")) +
  labs(caption = "Distribution of Effect Size Estimates (lnRR)",
       x = "lnRR",
       y = "Frequency")

print(lnRR_dist_plot)
```


```{r}
## Dependent effect size estimates
# Create phylogenetic tree

data <- as.data.frame(data)

data$species_latin = as.factor(data$species_latin)

taxa <- tnrs_match_names(names = levels(data$species_latin), context = "Animals")  # Match species names to the Open Tree of Life taxonomy

kable(taxa)  # Display matched species, ensuring each species has a unique match in the Open Tree of Life

taxa$unique_name <- gsub(" ", "_", taxa$unique_name)  # Replace spaces in species names with underscores

phylo_tree <- tol_induced_subtree(ott_ids = taxa$ott_id, label_format = "name")  # Generate a phylogenetic tree based on the Open Tree of Life taxonomy

ott_in_tree <- ott_id(taxa)[is_in_tree(ott_id(taxa))]  # Ensure all identifiers are present in the taxonomy

phylo_tree <- tol_induced_subtree(ott_ids = ott_in_tree)  # Generate a phylogenetic tree including all species present in the taxonomy

is.binary(phylo_tree)  # Check if tree is binary 


# Plot for the phylogenetic tree
plot(phylo_tree,
     cex= 1, #font size
     label.offset =.1,
     no.margin = TRUE)

# Compute branch length
phylo_branched <- compute.brlen(phylo_tree, method = "Grafen", power = 1)  # compute branch lengths using Grafen's method

phylo_branched$tip.label <- strip_ott_ids(phylo_branched$tip.label, remove_underscores = FALSE)  # remove ott ID from species name to match it to the data set

phylo_matrix <- vcv(phylo_branched, cor = T)  # Generate variance covariance matrix to correlate species relatedness 

data <- as.data.frame(data)
data <- data[, !duplicated(names(data))]

# Convert species_latin to lowercase
data <- mutate(data, search_string = tolower(species_latin))

data <- left_join(data, select(taxa, search_string, unique_name, ott_id), by = "search_string")  # Join data sets

data <- data[data$unique_name %in% phylo_branched$tip.label, ]  # Check that species names are well matched with the phylogenetic tree


data$phylogeny <- data$unique_name  # Rename 'unique_name' to 'phylogeny' for the models

```


```{r}
## Variance covariance matrices
# To account for the dependency of effect sizes estimates due to being in the same exposure group (cohort) we constructed a series of vcv matrices.

#------------------------------lnRR------------------------------#
data<- data[!is.na(data$lnRRv),] 
lnRRVCV <- metafor::vcalc(vi = lnRRv, cluster = exposure_id, obs = assay_id, data = data, rho = 0.5)
lnRRVCV <- lnRRVCV + diag(1e-5, nrow(lnRRVCV))

#SMD
data <- data[!is.na(data$SMDv),]

SMDVCV <- metafor::vcalc(vi      = SMDv,
                         cluster = exposure_id,
                         obs     = assay_id,
                         data    = data,
                         rho     = 0.5)

```

```{r}
#Inrercept-only SMD
SMD_intercept_only <- rma.mv(yi = SMD,
                             V  = SMDVCV,
                             random = list(~1 | study_id,
                                           ~1 | assay_id,
                                           ~1 | pharmaceutical_class,
                                           ~1 | species_latin,
                                           ~1 | phylogeny),
                             method = "REML",
                             test = "t",
                             data = data,
                             sparse = TRUE,
                             R = list(phylogeny = phylo_matrix))

summary(SMD_intercept_only)
```

```{r}
# Immune category
SMD_immune_category <- rma.mv(yi = SMD,
                             V  = SMDVCV,
                             random = list(~1 | study_id,
                                           ~1 | assay_id,
                                           ~1 | pharmaceutical_class,
                                           ~1 | species_latin,
                                           ~1 | phylogeny),
                             mods = ~immune_category_high -1,
                             method = "REML",
                             test = "t",
                             data = data,
                             sparse = TRUE,
                             R = list(phylogeny = phylo_matrix))

summary(SMD_immune_category)
```




```{r}
# Pharmaceutical classes
SMD_pharma <- rma.mv(yi = SMD,
                             V  = SMDVCV,
                             random = list(~1 | study_id,
                                           ~1 | assay_id,
                                           ~1 | pharmaceutical_class,
                                           ~1 | species_latin,
                                           ~1 | phylogeny),
                             mods = ~pharmaceutical_class -1,
                             method = "REML",
                             test = "t",
                             data = data,
                             sparse = TRUE,
                             R = list(phylogeny = phylo_matrix))

summary(SMD_pharma)

```

```{r}
SMD_phylogeny <- rma.mv(yi = SMD,
                             V  = SMDVCV,
                             random = list(~1 | study_id,
                                           ~1 | assay_id,
                                           ~1 | pharmaceutical_class,
                                           ~1 | species_latin,
                                           ~1 | phylogeny),
                             mods = ~phylogeny -1,
                             method = "REML",
                             test = "t",
                             data = data,
                             sparse = TRUE,
                             R = list(phylogeny = phylo_matrix))

summary(SMD_phylogeny)
```

```{r}
SMD_sex <- rma.mv(yi = SMD,
                             V  = SMDVCV,
                             random = list(~1 | study_id,
                                           ~1 | assay_id,
                                           ~1 | pharmaceutical_class,
                                           ~1 | species_latin,
                                           ~1 | phylogeny),
                             mods = ~sex -1,
                             method = "REML",
                             test = "t",
                             data = data,
                             sparse = TRUE,
                             R = list(phylogeny = phylo_matrix))

summary(SMD_sex)
```

```{r}
#age
## Recode age -> merge juvenile/embryo/larvae/eggs into "early_life_stage"
data <- data %>%
  mutate(
    age = tolower(str_trim(age)),
    age_recode = case_when(
      age %in% c("juvenile", "embryo", "larvae", "eggs") ~ "early_life_stage",
      age %in% c("adult", "not reported") ~ age,
      TRUE ~ "not reported"           # catch-all
    ),
    # choose reference level you prefer (here: "adult")
    age_recode = factor(age_recode, levels = c("adult","early_life_stage","not reported"))
  )

# model
SMD_age <- rma.mv(yi = SMD,
                             V  = SMDVCV,
                             random = list(~1 | study_id,
                                           ~1 | assay_id,
                                           ~1 | pharmaceutical_class,
                                           ~1 | species_latin,
                                           ~1 | phylogeny),
                             mods = ~age_recode -1,
                             method = "REML",
                             test = "t",
                             data = data,
                             sparse = TRUE,
                             R = list(phylogeny = phylo_matrix))

summary(SMD_age)

```

